Add support for multisubscriptions
Rapptz/discord.py pull request #10042
Opened 2024-12-12 19:09 UTC by DA-344

## Summary

Adds support for multi-subscriptions.

DDevs PR: https://github.com/discord/discord-api-docs/pull/7304

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2025-01-15 23:31 UTC, Rapptz requested changes

2025-01-15 23:31 UTC, Rapptz commented on discord/subscription.py
> +        The IDs of the SKUs that the user is going to be subscribed to when renewing.
Needs versionadded.

2025-01-15 23:31 UTC, Rapptz commented on discord/types/subscription.py
> +    renewal_sku_ids: List[Snowflake]
```suggestion
    renewal_sku_ids: Optional[List[Snowflake]]
```

Kind of weird this is considered a required key on their end but this is more accurate I guess.

2025-01-19 09:14 UTC, DA-344 commented on discord/subscription.py
> +        The IDs of the SKUs that the user is going to be subscribed to when renewing.
Oh, I didn't add it because the Subscription object is new on 2.5 too...

2025-01-19 09:19 UTC, Rapptz commented on discord/subscription.py
> +        The IDs of the SKUs that the user is going to be subscribed to when renewing.
Yeah that's fair, it's been forever since a release was cut so it's easy to forget lol

2025-01-19 09:21 UTC, Rapptz approved these changes
This looks okay, it's a bit low level though so it doesn't feel particularly useful though the state of the library at this point when it comes to this is something I'm still fighting in my head. Anyway, doesn't impact this PR so it's good to go.

2025-01-19 09:22 UTC, merged