fix message_pin, message_unpin target id being None
Rapptz/discord.py pull request #10061
Opened 2024-12-29 14:37 UTC by iyad-f

## Summary

This PR adds a check to AuditLogEntry._convert_target_message for handling None target_id.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2024-12-29 17:55 UTC, mikeshardmind requested changes

2024-12-29 17:55 UTC, mikeshardmind commented on discord/audit_logs.py
> +    def _convert_target_message(self, target_id: Optional[int]) -> Optional[Union[Member, User, Object]]:
```suggestion
    def _convert_target_message(self, target_id: Optional[int]) -> Union[Member, User, Object, None]:
```

2024-12-29 17:55 UTC, mikeshardmind commented on discord/audit_logs.py
>          return self._get_member(target_id) or Object(id=target_id, type=Member)
```suggestion
        return target_id and self._get_member(target_id) or Object(id=target_id, type=Member)
```

2024-12-29 19:09 UTC, Error44s commented
I took a look at it and changed it for me, I don't know if that could go through as a possible fix.

[5c7faa1](https://github.com/Error44s/discord.py/commit/5c7faa17368755904624a3526b923fcf149ee0fc)

2024-12-29 19:12 UTC, iyad-f commented
if target_id is None we just return None just like AuditLogAction._convert_target_user

2024-12-29 19:27 UTC, Error44s commented
In this case it is then one of the two or simply copy the one from AuditLogAction._convert_target_user ig.

```py
def _convert_target_message(self, target_id: Optional[int]) -> Union[Member, User, Object, None]:
    if target_id is None:
        return None  # Explicitly handle None
    return self._get_member(target_id) or Object(id=target_id, type=Member)
```

or

```py
def _convert_target_message(self, target_id: Optional[int]) -> Union[Member, User, Object, None]:
    return None if target_id is None else self._get_member(target_id) or Object(id=target_id, type=Member)
```

2025-01-25 19:09 UTC, AbstractUmbra commented on discord/audit_logs.py
> +        return target_id and self._get_member(target_id) or Object(id=target_id, type=Member)
```suggestion
        return target_id and (self._get_member(target_id) or Object(id=target_id, type=Member))
```

Order of precedence is causing this to type error.

2025-01-25 19:12 UTC, iyad-f commented on discord/audit_logs.py
> +        return target_id and self._get_member(target_id) or Object(id=target_id, type=Member)
Opps i didn’t take a look at those failures, thnx

2025-02-09 01:47 UTC, merged