Add 6 new message types
Rapptz/discord.py pull request #5200
Opened 2020-08-05 18:42 UTC by NCPlayz

### Summary

Adds:
```
    guild_stream                                 = 13
    guild_discovery_disqualified                 = 14
    guild_discovery_requalified                  = 15
    guild_discovery_grace_period_initial_warning = 16
    guild_discovery_grace_period_final_warning   = 17
    thread_created                               = 18
```

### Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2020-11-25 15:05 UTC, PikalaxALT requested changes

2020-11-25 15:05 UTC, PikalaxALT commented on docs/api.rst
> +        .. versionadded:: 1.4
Bump to 1.6

2020-11-25 15:05 UTC, PikalaxALT commented on docs/api.rst
> +        .. versionadded:: 1.4
Document the reply type here

2020-11-25 15:28 UTC, NCPlayz commented
Thanks for the review @PikalaxALT, this PR was mainly put on hold due to the inclusion of the thread message type (along with #5201) which hasn't become official yet, so I might move thread related features to another PR and bump this one since the reply type is a priority at the moment.

2021-02-22 19:11 UTC, NCPlayz commented
Removed thread and reply message types as they require an API version bump to v8. The rest of the types still present can be gracefully merged into 1.7.

2021-02-23 08:57 UTC, merged