[commands] add require_var_positional
Rapptz/discord.py pull request #5793
Opened 2020-09-05 20:09 UTC by khazhyk

Allow command require_var_positional=True to require[commands] add require_var_positional

Add command require_var_positional=True to require at least one
argument to var_positional argument types.
Defaults to False, as previous behavior.

### Summary

https://github.com/Rapptz/discord.py/pull/967 for the new branch

### Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2020-09-06 04:27 UTC, Rapptz requested changes

2020-09-06 04:27 UTC, Rapptz commented on discord/ext/commands/core.py
> +        If ``True`` and a varadic positional argument is specified, requires
```suggestion
        If ``True`` and a variadic positional argument is specified, requires the
```

2020-09-06 04:27 UTC, Rapptz commented on discord/ext/commands/core.py
> +        user specifies at least one argument instead of allowing zero. Defaults
```suggestion
        user to specify at least one argument. Defaults to ``False``.
```

2020-09-06 04:27 UTC, Rapptz commented on discord/ext/commands/core.py
> +        to ``False``.
Needs a `.. versionadded:: 1.5` somewhere here.

2020-09-07 20:21 UTC, khazhyk commented
Thanks for the review, updated

2020-09-08 02:24 UTC, merged