Add support for bot integrations.
Rapptz/discord.py pull request #5874
Opened 2020-09-30 23:22 UTC by XuaTheGrate

## Summary

Adds support for bot integrations. I'm not entirely confident about the design, so feedback welcome.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2020-11-23 23:50 UTC, NCPlayz requested changes
Noticed missing `versionadded` on the two new `Integration` attributes

2020-11-23 23:50 UTC, NCPlayz commented on discord/integrations.py
> +        The user for the integration. In the case of a bot application, this is the person who invited it.
```suggestion
        The user for the integration. In the case of a bot application, this is the person who invited it.
        
        .. versionadded:: 2.0
```

2020-11-23 23:50 UTC, NCPlayz commented on discord/integrations.py
> +        The application this integration belongs to. Can be ``None`` if it is not a bot integration.
```suggestion
        The application this integration belongs to. Can be ``None`` if it is not a bot integration.
        
        .. versionadded:: 2.0
```

2021-04-11 20:14 UTC, NCPlayz commented on discord/http.py
> +        r = Route('GET', '/guilds/{guild_id}/integrations?include_applications=True', guild_id=guild_id)
```suggestion
        r = Route('GET', '/guilds/{guild_id}/integrations', guild_id=guild_id)
```

applications integrations are provided by default now.

2021-04-11 21:59 UTC, NCPlayz requested changes

2021-04-11 21:59 UTC, NCPlayz commented on discord/integrations.py
> +        self.type = integration_type = integ['type']
```suggestion
        self.type = integ['type']
```

2021-04-11 21:59 UTC, NCPlayz commented on discord/integrations.py
> +            self.application = Application(**application)
```suggestion
            self.application = Application(state=self._state, data=application)
```

2021-04-11 21:59 UTC, NCPlayz commented on discord/integrations.py
> +        return '<Application id={0.id} name={0.name!r} bot={0.bot!r}>'.format(self)
```suggestion
        return f'<Application id={self.id} name={self.name!r} bot={self.bot!r}>'
```

2021-04-11 21:59 UTC, NCPlayz commented on discord/integrations.py
> +        self.bot = User(state=state, data=data['bot'])
```suggestion
        bot = data.get('bot')
        if bot is not None:
            self.bot = User(state=self._state, data=bot)
        else:
            self.bot = None
```

2021-04-11 21:59 UTC, NCPlayz commented on discord/integrations.py
> +        application = integ.get('application')
Maybe move this just before the application check?

2021-04-12 03:00 UTC, Rapptz requested changes

2021-04-12 03:00 UTC, Rapptz commented on discord/integrations.py
> +    )
```suggestion
    __slots__ = Integration.__slots__ + ('application',)
```

2021-04-12 04:47 UTC, NCPlayz requested changes
Seems like `__repr__` went missing for the classes, and you might also want to change the object creation at `Guild.integrations` to use the new integration classes now.

The new classes should probably also be added to `__all__` and `autoclass`'d in the API Reference.

2021-04-12 04:47 UTC, NCPlayz commented on discord/integrations.py
> +)
```suggestion
    )
```

2021-04-16 03:09 UTC, Rapptz approved these changes

2021-04-16 03:09 UTC, Rapptz commented on discord/integrations.py
> +        self.id: int = _get_as_snowflake(data, 'id')
```suggestion
        self.id: int = int(data['id'])
```

2021-05-29 04:43 UTC, Rapptz commented
I decided to fix these review nits myself. Thanks for the PR.

2021-05-29 04:43 UTC, merged