uncomment intents examples
Rapptz/discord.py pull request #6023
Opened 2020-11-08 22:14 UTC by XuaTheGrate

## Summary

A lot of people in the help channel seem to not realize you need to pass the intents into the constructor. Uncommenting this may help.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2020-11-08 22:15 UTC, NCPlayz commented
Whilst you're at it, wouldn't it be better if these lines were highlighted as well?

2020-11-08 22:19 UTC, Rapptz commented
It wasn't uncommented because the "copy paste code blindly" group would now have two client instances and swap between them -- an already prevalent issue.

2020-11-08 22:29 UTC, XuaTheGrate commented
Made the changes, though GitHub rst preview won't show these changes so I don't actually know if it worked.

2020-11-11 20:13 UTC, NCPlayz requested changes
A slight miscalculation on the line numbers.

2020-11-11 20:13 UTC, NCPlayz commented on docs/intents.rst
> +   :emphasize-lines: 3,5,7,8
```suggestion
   :emphasize-lines: 3,6,8,9
```

2020-11-11 20:13 UTC, NCPlayz commented on docs/intents.rst
> +   :emphasize-lines: 6,8,9
```suggestion
   :emphasize-lines: 7,9,10
```

2020-11-22 03:19 UTC, closed without merging