add description kwarg in CogMeta
Rapptz/discord.py pull request #6028
Opened 2020-11-10 11:46 UTC by SebbyLaw

## Summary

Resolves #6024

Not sure if this is considered a breaking change or not.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2020-11-10 14:31 UTC, ShineyDev commented
To resolve the linked issue this PR should also make Cog.description a writable property.

> Not sure if this is considered a breaking change or not.

Adding a new optional kwarg is not a breaking change.

2020-11-22 02:37 UTC, Rapptz requested changes
I prefer having the property rather than a plain class attribute since this makes it less likely for the user to shoot themselves on the foot when they write e.g. `cog.description = "hi"` which should error out since it did before. I guess it's up to debate whether having it read-only is necessary though.

This probably also needs a versionadded.

2020-11-22 02:37 UTC, Rapptz commented on discord/ext/commands/cog.py
> +        attrs['description'] = description = kwargs.pop('description', None)
```suggestion
        attrs['__cog_description__'] = description = kwargs.pop('description', None)
```

2020-11-22 02:37 UTC, Rapptz commented on discord/ext/commands/cog.py
> +            attrs['description'] = inspect.getdoc(cls)
```suggestion
            attrs['__cog_description__'] = inspect.cleandoc(attrs.get('__doc__', ''))
```

2020-11-22 02:37 UTC, Rapptz commented on discord/ext/commands/cog.py
> +        Returns the cog's description, typically the cleaned docstring.
```suggestion
```

2020-11-23 10:12 UTC, Rapptz requested changes
If this is meant to be modifiable then adding a property setter would probably work at this point.

2020-11-23 10:12 UTC, Rapptz commented on discord/ext/commands/cog.py
> +            attrs['__cog_description__'] = inspect.cleandoc(attrs.get('__doc__', ''))
```suggestion
        description = kwargs.pop('description', None)
        if description is None:
            description = inspect.cleandoc(attrs.get('__doc__', ''))
        attrs['__cog_description__'] = description
```

2020-11-26 05:13 UTC, Rapptz approved these changes

2020-11-26 15:49 UTC, Harmon758 commented
This was merged with https://github.com/Rapptz/discord.py/commit/4adbe03d7ca03fce3411bea7bcd9e3619513ad94 and can be closed now.

2020-11-26 19:35 UTC, closed without merging