Add feature  url_as for emoji
Rapptz/discord.py pull request #6162
Opened 2020-12-13 17:03 UTC by Daggy1234

## Summary

Adds a new method for an emoji named `url_as` to allow a user to customize the emoji asset produced. It does this by adding a `_from_emoji` classmethod for Asset. It also modifies the way `emoji.url` is accessed.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2020-12-14 11:47 UTC, numbermaniac commented on discord/emoji.py
> +            Bad image format passed to ``format`` or ``static_format``
```suggestion
            Bad image format passed to ``format`` or ``static_format``.
```

2020-12-14 11:48 UTC, numbermaniac commented on discord/emoji.py
> +            Format to attempt to convert only non-animated emoji's to.
```suggestion
            The format to attempt to convert non-animated emojis to.
```
"only" is _probably_ unnecessary here.

2020-12-14 11:53 UTC, SebbyLaw commented on discord/emoji.py
> +        'gif' is only valid for animated emojis.
```suggestion
        The format must be one of 'webp', 'jpeg', 'jpg', 'png' or 'gif'.
        'gif' is only valid for animated emojis. 
```

2020-12-14 11:57 UTC, numbermaniac commented on discord/emoji.py
> +            emoji being animated or not.
```suggestion
            If the format is ``None``, then it is automatically
            detected as either 'gif' or static_format, depending on if the
            emoji is animated or not.
```

2020-12-14 15:41 UTC, NCPlayz requested changes

2020-12-14 15:41 UTC, NCPlayz commented on discord/emoji.py
> +    def url_as(self,*,format=None,static_format="png"):
```suggestion
    def url_as(self, *, format=None, static_format="png"):
```

2020-12-15 02:56 UTC, Daggy1234 commented on discord/emoji.py
> +            emoji being animated or not.
Replaced the `if` with a `wether`

2020-12-15 03:26 UTC, SebbyLaw commented on discord/emoji.py
> +        ------
```suggestion
        -------
```
Add one hyphen to match the format of the rest of the library.

2020-12-18 03:20 UTC, merged