[commands] Correct concurrency never releasing during prepare call
Rapptz/discord.py pull request #6190
Opened 2020-12-23 19:32 UTC by Phxntxm

## Summary

This corrects an issue where concurrency is never released when the `prepare` method is called. This test case shows the issue:

```
bot = commands.Bot(command_prefix=">")

@bot.command()
@commands.max_concurrency(1, per=commands.BucketType.user)
async def test(ctx, argument):
    await ctx.send("test")
```

During this if you use `>test` then MissingRequiredArgument is raised. Since this happens during `prepare` (before this PR) MaxConcurrency.release is never called (since that happens during [the hooked_wrapped_callback](https://github.com/Rapptz/discord.py/blob/eb11079569570ce991d9468ca40eb8fcf129e0be/discord/ext/commands/core.py#L95-L97) call which happens [later in the invoke method](https://github.com/Rapptz/discord.py/blob/eb11079569570ce991d9468ca40eb8fcf129e0be/discord/ext/commands/core.py#L858)), leading to any subsequent calls to this raising MaxConcurrencyReached.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2020-12-25 07:20 UTC, Rapptz requested changes
The idea behind this changeset is good.

However, the current implementation uses `invoke` which is an injection point for groups as well. Doing this changeset in both places is not desirable to me and it should instead be entirely self-contained somewhere else.

2020-12-25 20:52 UTC, Phxntxm commented
(Oops I completely forgot about groups)

For the sake of sense it feels like acquiring should be the very first thing that happens and releasing the very last thing that happens. Which then feels to me like it should properly be here: <https://github.com/Rapptz/discord.py/blob/master/discord/ext/commands/bot.py#L900-L908> (the release in an added finally) but current implementation has `_max_concurrency` as a private attribute. 

Would changing that to a public attribute and moving it here be an acceptable fix? Or if not, including methods in the Command class for acquiring and releasing be instead? If not either of those, I guess it can be thrown in `prepare` since Group does not override that method

2020-12-26 07:32 UTC, Rapptz commented
Changing it in `prepare` is probably for the best. Another entry point is probably `Command.dispatch_error` but it feels out of place and can potentially lead to multiple release calls.

2020-12-27 01:58 UTC, Rapptz approved these changes

2020-12-27 01:58 UTC, merged