Update add_roles docstring to mention role order.
Rapptz/discord.py pull request #6284
Opened 2021-01-10 03:59 UTC by perrycate

## Summary

Adds a quick mention of the relevance of discord's role ordering. When I tried to use this function, I had no idea that that mattered until I eventually found [this comment](https://github.com/Rapptz/discord.py/issues/1814#issuecomment-451047619) in issue #1814.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-01-12 07:33 UTC, Rapptz requested changes
I think in the future this might be better suited with a page describing the intricacies of role hierarchy.

For now though, could this also be mentioned in `remove_roles`? It's basically the same concept -- you can't remove roles higher than the member.

2021-01-12 07:33 UTC, Rapptz commented on discord/member.py
> +        of roles than the highest role of the caller.
```suggestion
        of roles than the highest role of the member.
```

2021-01-13 22:35 UTC, perrycate commented on discord/member.py
> +        of roles than the highest role of the caller.
Done.

2021-01-14 08:11 UTC, Rapptz approved these changes

2021-01-14 08:11 UTC, merged