Implement PartialMessage.edit
Rapptz/discord.py pull request #6309
Opened 2021-01-14 17:48 UTC by anurag-7

## Summary

This PR implements a separate `edit` method for `PartialMessage` which returns a `Message` Object on edit. Additionally the `flags` on this edit will default since `ParitalMessage.flags` attribute doesn't exist, closes #6276.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-01-14 17:51 UTC, bijij commented on discord/message.py
> +        :class:`Message`
This is returned optionally.

2021-01-14 17:55 UTC, NCPlayz commented on discord/message.py
> +            return self._state.create_message(channel=self.channel, data=data)
```suggestion
            return self._state.create_message(channel=self.channel, data=data)

```

2021-01-15 04:27 UTC, bijij approved these changes

2021-01-15 10:32 UTC, Rapptz requested changes

2021-01-15 10:32 UTC, Rapptz commented on discord/message.py
> +            :class:`discord.Message` is returned instead of ``None`` on edit.
```suggestion
            :class:`discord.Message` is returned instead of ``None`` if an edit took place.
```

2021-01-15 12:09 UTC, Rapptz approved these changes

2021-01-15 12:09 UTC, Rapptz commented
It is a bit unfortunate that this ended up being duplicate code.

2021-01-15 12:10 UTC, merged