deprecate non-bot methods
Rapptz/discord.py pull request #6454
Opened 2021-02-21 22:55 UTC by NCPlayz

## Summary

This PR aims to deprecate the non-bot methods in preparation for their removal at v2.0. 
I'm sure I missed something so critique welcome.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-02-22 08:03 UTC, Rapptz commented
This is missing `GroupCall` and `Message.call` which also deal with user bots. I'm not really sure what else there is.

Note however that "deprecated" is already a built-in Sphinx directive, [it works similarly to versionchanged](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-deprecated) and should be what is used here, not a note directive.

2021-02-22 10:07 UTC, Rapptz requested changes
Need to deprecate the `Message.call` attribute as well.

2021-02-22 10:18 UTC, Zomatree commented
Will we also deprecate the `bot` kwarg in `Client.run/start/login` for logging into a user account?

2021-02-23 08:36 UTC, Rapptz approved these changes

2021-02-23 08:36 UTC, merged