inject state into PartialEmoji in Activity
Rapptz/discord.py pull request #6466
Opened 2021-02-22 22:14 UTC by SebbyLaw

## Summary

Resolves #4017

## Checklist

- [x] If code changes were made then they have been tested.
    - [N/A] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-02-22 23:00 UTC, SebbyLaw commented
Maybe using tuple comprehension would be better than constructing `itertools.repeat` every time.

2022-03-06 04:53 UTC, SebbyLaw commented
Updated to fix merge conflicts and typing overloads

2022-03-07 07:04 UTC, Rapptz requested changes

2022-03-07 07:04 UTC, Rapptz commented on discord/member.py
> +        self.activities = tuple(map(create_activity, data['activities'], itertools.repeat(self._state)))
```suggestion
        self.activities = tuple(create_activity(d, self._state) for d in data['activities'])
```

2022-03-11 01:55 UTC, Rapptz approved these changes

2022-03-11 01:56 UTC, merged