Update docs for discord.Invite.max_uses
Rapptz/discord.py pull request #6486
Opened 2021-02-27 00:20 UTC by xPolar

## Summary

Previously there was no indicator for if an invite can be used infinitely, update it to tell users 0 indicates infinite uses.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-02-27 00:21 UTC, SebbyLaw commented on discord/invite.py
> +        How many times the invite can be used. A value of 0 indicates that an infinite number of people can use the invite.
```suggestion
        How many times the invite can be used.
        A value of ``0`` indicates that an infinite number of people can use the invite.
```

2021-02-27 00:22 UTC, Phxntxm commented
![image](https://user-images.githubusercontent.com/3664828/109368670-55f38a80-7846-11eb-992d-f47de93b2256.png)
Hmm? It's right there, where it actually matters, on `create_invite`

2021-02-27 00:23 UTC, xPolar commented
![image](https://i.imgur.com/rXuVNRC.png)

2021-02-27 00:26 UTC, SebbyLaw approved these changes

2021-02-27 00:27 UTC, fwrs approved these changes

2021-02-27 00:38 UTC, xPolar commented
Meant to say Sebby's changes but accidentally pressed enter.

2021-03-01 04:34 UTC, Rapptz requested changes

2021-03-01 04:34 UTC, Rapptz commented on discord/invite.py
> +        A value of ``0`` indicates that an infinite number of people can use the invite.
```suggestion
        A value of ``0`` indicates that it has unlimited uses.
```

2021-03-01 04:34 UTC, Rapptz approved these changes

2021-03-01 04:35 UTC, merged