Add Permissions attributes
Rapptz/discord.py pull request #6497
Opened 2021-03-01 15:41 UTC by TheOneMusic

## Summary

This pull request adds these new things:
- `Permissions.default()` which corresponds to the default Discord permissions for roles
- Possibility to add and subtract [`Permissions`](https://github.com/Rapptz/discord.py/blob/master/discord/permissions.py#L47) directly. For example, we can now use `Permissions.text() + Permissions.voice()` to make a [`Permissions`](https://github.com/Rapptz/discord.py/blob/master/discord/permissions.py#L47) with all text and voice permissions, or `Permissions.all() - Permissions.general()` to make a [`Permissions`](https://github.com/Rapptz/discord.py/blob/master/discord/permissions.py#L47) with every permissions, except the **General** permissions. This is helpful to avoid dealing with [`Permissions.update()`](https://github.com/Rapptz/discord.py/blob/master/discord/permissions.py#L217) when adding/subtracting [`Permissions`](https://github.com/Rapptz/discord.py/blob/master/discord/permissions.py#L47) instances directly.
- Boolean method which returns `True` if and only if there are permissions (permission value different from 0), and `is_empty` method that returns the opposite - similar to [`PermissionOverwrite.is_empty()`](https://github.com/Rapptz/discord.py/blob/master/discord/permissions.py#L561)

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-03-01 16:09 UTC, NCPlayz requested changes
Trailing whitespace.

2021-03-01 16:09 UTC, NCPlayz commented on discord/permissions.py
> +
```suggestion

```

2021-03-01 16:09 UTC, NCPlayz commented on discord/permissions.py
> +
```suggestion

```

2021-03-13 05:45 UTC, Rapptz commented
I'm not really a fan of these.

1. `default()` is more work to maintain with the UI changes.
2. I don't really think adding or removing permissions via subtraction and addition is a good interface. 
3. `is_empty` doesn't conceptually make sense on `Permissions`, whereas an overwrite can be empty and disengaged.
4. I'm neutral on `__bool__`, I think it could be handy but I'm not really sure.

2021-03-13 05:45 UTC, closed without merging