[docs] suggest presence in constructor instead of change_presence
Rapptz/discord.py pull request #6589
Opened 2021-03-30 06:45 UTC by sgtlaggy

## Summary

Change the `How do I set the “Playing” status?` FAQ entry to point out the `activity` keyword arg in the `Client` constructor.
Also replaces the examples to show setting the activity by the constructor instead of `change_presence`.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-03-30 07:59 UTC, Rapptz requested changes
I think this is okay but removing the dynamic presence changing is also a bit odd. Some people want to be able to change their presences at runtime as well and this doesn't really point them to that direction.

2021-03-30 07:59 UTC, Rapptz commented on docs/faq.rst
> +    Discord has a high chance to completely disconnect you during the ``READY`` or ``GUILD_CREATE`` events (``1006`` close code) and there is nothing you can do to prevent it.
```suggestion
    There is a high chance of disconnecting if presences are changed right after connecting.
```

I want to keep specifics and theory guessing out of it. I don't actually know why it disconnects you (I've tried figuring it out to no avail).

2021-03-30 17:45 UTC, sgtlaggy commented
> Some people want to be able to change their presences at runtime as well and this doesn't really point them to that direction.

I feel like this is something users should be expected to extrapolate from the information given. `change_presence` is mentioned in the answer still, and its usage is no different from passing activity via the constructor.
Maybe the second line could be rewritten to "`change_presence` may be used to change the activity after the bot has started."

My main idea with the PR is to steer users away from using `change_presence` in cases where they don't need it. If they only see an example using the `Client` class, but they're using the `Bot` class, most of the users this PR targets will likely ignore that and go straight for the `change_presence` example.

2021-03-31 00:22 UTC, Rapptz commented
As it stands this entry recommends `activity` without actually detailing the difference between it and `change_presence`. If the wording could be modified slightly then I'd be fine with it.

2021-04-01 01:26 UTC, Rapptz approved these changes
Thanks. This is good enough.

2021-04-01 01:26 UTC, merged