Implement StageChannel and related methods
Rapptz/discord.py pull request #6608
Opened 2021-04-01 13:48 UTC by NCPlayz

## Summary

Implements the new features as part of channel type ``13``, guild stage voice channels.
Reviews welcome.

Additions:

- `ChannelType.stage_voice`
- `StageChannel`
- `StageChannelConverter`
- `Guild.stage_channels`
- `Guild.create_stage_channel`
- `CategoryChannel.create_stage_channel`
- `Member.request_to_speak`
- `Member.edit(suppress=True | False)`
- `VoiceState.suppress`
- `VoiceState.requested_to_speak_at`
- `Permissions.stage_moderator()`

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-04-01 13:58 UTC, Rapptz requested changes
I haven't tested it but the code seems mostly ok

2021-04-01 13:58 UTC, Rapptz commented on discord/member.py
> +    channel: Optional[:class:`VoiceChannel`, :class:`StageChannel`]
```suggestion
    channel: Optional[Union[:class:`VoiceChannel`, :class:`StageChannel`]]
```

2021-04-01 22:20 UTC, Tari-dev commented
ummmm... GuildVocalChannel sounds better than VocalGuildChannel.

2021-04-01 22:22 UTC, diceroll123 commented
> ummmm... GuildVocalChannel sounds better than VocalGuildChannel.

*Sounds* better, but it is a GuildChannel at its base.

2021-04-01 22:27 UTC, Rapptz commented
It's not exposed publicly so it's name does not matter.

2021-04-01 22:43 UTC, diceroll123 commented
Gotta update `Permissions.all()` to include 1 << 32

2021-04-04 02:42 UTC, Rapptz approved these changes
Looks good. I'll manually commit the one suggestion I have.

2021-04-04 02:42 UTC, Rapptz commented on discord/channel.py
> +    def requests_to_speak(self):
```suggestion
    def requesting_to_speak(self):
```

2021-04-04 02:43 UTC, merged