Add subcommands example
Rapptz/discord.py pull request #6611
Opened 2021-04-02 16:23 UTC by pikaninja

## Summary

Adds an example code for subcommands

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-04-02 16:38 UTC, NCPlayz requested changes
Few wording tidbits, formatting, as well as using `'` instead of `"` when not needed.

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# Because we made our group seperate, checks will not carry over from the parent command
```suggestion
# Because we made our group separate, checks will not carry over from the parent command
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# This would be invoked with `?greet goodbye @Example#0000`
```suggestion
# This would be invoked with `?greet goodbye <member>`
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# Our bot object
```suggestion
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# Defining our subcommand as an command of our group
```suggestion
# Defining our subcommand as a command of our group
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# We can define additional checks here
```suggestion
# We can define additional checks specific to this subcommand
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# We can also do sub sub commands!
```suggestion
# We can also nest groups!
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# Define our sub sub command
```suggestion
# Define our nested subcommand
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# Sometimes we want our subcommands to function indenpendently from our subcommands
```suggestion
# Sometimes you may want a subcommand to function independently from the rest
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# To do this, we can use the `invoke_without_command` kwarg
```suggestion
# To do this, we can use the `invoke_without_command` keyword argument
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +# When set to True, the parent command will only be invoked when subcommands aren't
```suggestion
# When set to `True`, the parent command will only be invoked when no subcommand is found
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +@bot.group(invoke_without_command = True)
```suggestion
@bot.group(invoke_without_command=True)
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +@commands.has_guild_permissions(manage_roles = True)
```suggestion
@commands.has_guild_permissions(manage_roles=True)
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +    await ctx.send("Done!")
```suggestion
    await ctx.send('Done!')
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +    roles = "\n".join(r.mention for r in member.roles)
```suggestion
    roles = '\n'.join(r.mention for r in member.roles)
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +        "{0} Currently has:\n {1}".format(member, roles),
```suggestion
        '{0} Currently has:\n {1}'.format(member, roles),
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +    await ctx.send("Hello everyone!")
```suggestion
    await ctx.send('Hello everyone!')
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +    await ctx.send("Goodbye {0.author}".format(member))
```suggestion
    await ctx.send('Goodbye {0.author}'.format(member))
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +    await ctx.send("Hello {0.author}!".format(ctx))
```suggestion
    await ctx.send('Hello {0.author}!'.format(ctx))
```

2021-04-02 16:38 UTC, NCPlayz commented on examples/subcommands.py
> +@everyone.command(name = "hello")
```suggestion
@everyone.command(name="hello")
```

2021-04-06 03:34 UTC, ImVaskel requested changes

2021-04-06 03:34 UTC, ImVaskel commented on examples/subcommands.py
> +    await ctx.send(f'Goodbye {member.author}')
```suggestion
    await ctx.send(f'Goodbye {member}')
```
I assume this is just supposed to be `member`

2021-04-06 03:34 UTC, ImVaskel commented on examples/subcommands.py
> +
```suggestion
```
This whitespace isn't needed.

2022-03-06 04:14 UTC, pikaninja commented
i broke something idk

2022-03-06 04:14 UTC, closed without merging