Create new AutoShardedMixin for Client
Rapptz/discord.py pull request #6631
Opened 2021-04-05 06:24 UTC by bijij

## Summary

Creates a new `AutoShardedMixin` class.
Modifies MRO of AutoShardedClient and AutoShardedBot accordingly.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-04-05 06:26 UTC, NCPlayz requested changes

2021-04-05 06:26 UTC, NCPlayz commented on discord/client.py
> +
```suggestion
    pass

```

2021-04-05 07:01 UTC, Rapptz commented
Why?

2021-04-08 05:23 UTC, numbermaniac commented on discord/client.py
> +    :class:`Client` with a single shard when implementation wise internally it
```suggestion
    When using this client, you will be able to use it as if it was a regular
    :class:`Client` with a single shard, when implementation-wise internally it
```

2021-04-18 11:56 UTC, closed without merging