Add source_channel and source_guild to Webhook
Rapptz/discord.py pull request #6644
Opened 2021-04-06 03:57 UTC by Zomatree

## Summary

adds two attributes to webhooks

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-04-06 04:02 UTC, Rapptz requested changes
Some renames.

Note that newer code is typehinted, which this is missing. For now that's okay though.

2021-04-06 04:02 UTC, Rapptz commented on discord/webhook.py
> +    """Partial channel for webhooks
This needs more meat.

2021-04-06 04:02 UTC, Rapptz commented on discord/webhook.py
> +        The channel's name.
This should probably mention it's a partial webhook channel.

2021-04-06 04:02 UTC, Rapptz commented on discord/webhook.py
> +    """Partial guild for webhooks
This also needs more meat.

2021-04-06 04:02 UTC, Rapptz commented on discord/webhook.py
> +        return f'<PartialGuild name=\'{self.name}\' id={self.id}>'
```suggestion
        return f'<PartialWebhookGuild name={self.name!r} id={self.id}>'
```

2021-04-06 05:40 UTC, Rapptz requested changes

2021-04-06 05:40 UTC, Rapptz commented on discord/webhook.py
> +    """Partial channel for webhooks for when they are channel following webhooks for news channels.
This docstring doesn't match the rest of the codebase.

```suggestion
    """Represents a partial channel for webhooks.

    These are typically given for channel follower webhooks.
```

2021-04-06 05:40 UTC, Rapptz commented on discord/webhook.py
> +        return f'<PartialChannel name=\'{self.name}\' id={self.id}>'
```suggestion
        return f'<PartialWebhookChannel name={self.name!r} id={self.id}>'
```

Missed this.

2021-04-06 05:40 UTC, Rapptz commented on discord/webhook.py
> +        The guild of the channel that this webhook is following (returned for Channel Follower Webhooks).
```suggestion
        The guild of the channel that this webhook is following. Only given if :attr:`type` is :attr:`WebhookType.channel_follower`.
```

2021-04-06 05:40 UTC, Rapptz commented on discord/webhook.py
> +        The channel that this webhook is following (returned for Channel Follower Webhooks).
```suggestion
        The channel that this webhook is following. Only given if :attr:`type` is :attr:`WebhookType.channel_follower`.
```

2021-04-06 07:21 UTC, NCPlayz requested changes

2021-04-06 07:21 UTC, NCPlayz commented on discord/webhook.py
> +            source_channel = None
`source_channel` should be `None` here anyway (unless otherwise?).

2021-04-06 07:21 UTC, NCPlayz commented on discord/webhook.py
> +            source_guild = None
`source_guild` should be `None` here anyway (unless otherwise?).

2021-04-06 07:21 UTC, NCPlayz commented on discord/webhook.py
> +    source_guild: Optional[:class:`PartialGuild`]
```suggestion
    source_guild: Optional[:class:`PartialWebhookGuild`]
```

2021-04-06 07:21 UTC, NCPlayz commented on discord/webhook.py
> +    source_channel: Optional[:class:`PartialChannel`]
```suggestion
    source_channel: Optional[:class:`PartialWebhookChannel`]
```

2021-04-06 07:21 UTC, NCPlayz commented on discord/webhook.py
> +        The channel that this webhook is following. Only given if :attr:`type` is :attr:`WebhookType.channel_follower`.
```suggestion
        The channel that this webhook is following.
        Only given if :attr:`type` is :attr:`WebhookType.channel_follower`.
```

2021-04-06 07:21 UTC, NCPlayz commented on discord/webhook.py
> +        The guild of the channel that this webhook is following. Only given if :attr:`type` is :attr:`WebhookType.channel_follower`.
```suggestion
        The guild of the channel that this webhook is following.
        Only given if :attr:`type` is :attr:`WebhookType.channel_follower`.
```

2021-04-06 07:21 UTC, NCPlayz commented on discord/webhook.py
> +    """Partial guild for webhooks for when they are channel following webhooks for news channels.
```suggestion
    """Represents a partial guild for webhooks.

    These are typically given for channel follower webhooks.
```

2021-04-07 03:31 UTC, Rapptz approved these changes
LGTM.

2021-04-07 03:31 UTC, merged