Add invite targets for voice channel invites
Rapptz/discord.py pull request #6789
Opened 2021-04-25 11:33 UTC by Zomatree

## Summary

this adds support to create invites with a target (user or application) and attributes to access those from an invite.

## Checklist
- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-04-25 11:57 UTC, NCPlayz requested changes

2021-04-25 11:57 UTC, NCPlayz commented on discord/appinfo.py
> +    from .types.appinfo import AppInfo as AppInfoData
```suggestion
    from .types.appinfo import AppInfo as AppInfoPayload
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/appinfo.py
> +    def __init__(self, state, data: AppInfoData):
```suggestion
    def __init__(self, state, data: AppInfoPayload):
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/team.py
> +    from .types.team import Team as TeamData, TeamMember as TeamMemberData
```suggestion
    from .types.team import (
        Team as TeamPayload,
        TeamMember as TeamMemberPayload,
    )
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/team.py
> +    def __init__(self, state, data: TeamData):
```suggestion
    def __init__(self, state, data: TeamPayload):
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/team.py
> +    def __init__(self, team: Team, state, data: TeamMemberData):
```suggestion
    def __init__(self, team: Team, state, data: TeamMemberPayload):
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/appinfo.py
> +        from .team import Team
```suggestion
```

Unsure why this had to change?

2021-04-25 11:57 UTC, NCPlayz commented on discord/appinfo.py
> +            it is now Optional[:class:`User`] rather than :class:`User`
```suggestion
            This attribute is now optional.
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/invite.py
> +        the user whose stream to display for this invite, if any.
```suggestion
        The user whose stream to display for this invite, if any.
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/types/appinfo.py
> +
```suggestion
from .snowflake import Snowflake

```

2021-04-25 11:57 UTC, NCPlayz commented on discord/types/appinfo.py
> +    id: int
```suggestion
    id: Snowflake
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/types/team.py
> +
```suggestion
from .snowflake import Snowflake

```

2021-04-25 11:57 UTC, NCPlayz commented on discord/types/team.py
> +    id: int
```suggestion
    id: Snowflake
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/types/team.py
> +    owner_id: int
```suggestion
    owner_id: Snowflake
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/types/team.py
> +    team_id: str
```suggestion
    team_id: Snowflake
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/types/appinfo.py
> +    guild_id: str
```suggestion
    guild_id: Snowflake
```

2021-04-25 11:57 UTC, NCPlayz commented on discord/types/appinfo.py
> +    primary_sku_id: str
```suggestion
    primary_sku_id: Snowflake
```

2021-04-28 02:03 UTC, Rapptz requested changes
The diffs in this PR are, quite frankly, a complete mess. `api.rst` in particular seems to have needlessly re-ordered things for no good discernible reason. I'm not sure why there are team related changes in this PR as well. They can stay since they're already there but next time please don't do one thing per PR.

2021-04-28 02:03 UTC, Rapptz commented on discord/http.py
> +            payload['target_application_id'] = str(target_application)
Generally speaking, the only data types that I handle within `http.py` are `(str, int, float, bool, None, File)`. Attribute access and enums are done in the higher level methods before being passed down to the lower level http client.

2021-04-28 02:03 UTC, Rapptz commented on discord/invite.py
> +        self.target_application = AppInfo(data=application, state=state) if application else None
This entire diff needs work since it's needlessly overwriting someone's previous work. Also, single quotes not double quotes.

2021-04-28 02:24 UTC, numbermaniac commented on discord/abc.py
> +            the user whose stream to display for this invite, required if `target_type` is `TargetType.stream`. the user must be streaming in the channel.
```suggestion
            The user whose stream to display for this invite, required if `target_type` is `TargetType.stream`. The user must be streaming in the channel.
```

2021-04-28 02:25 UTC, numbermaniac commented on docs/api.rst
> +    .. vesionadded:: 2.0
```suggestion
    .. versionadded:: 2.0
```

2021-04-28 02:25 UTC, numbermaniac commented on docs/api.rst
> +    Represents the invite type for voice channel invites
```suggestion
    Represents the invite type for voice channel invites.
```

2021-04-28 15:43 UTC, Zomatree commented on discord/appinfo.py
> +            This attribute is now optional.
They dont always have owners, thus optional.

2021-05-01 18:06 UTC, Rapptz requested changes

2021-05-01 18:06 UTC, Rapptz commented on discord/abc.py
> +            fields["target_type"] = fields["target_type"].value
```suggestion
        if 'target_type' in fields:
            fields['target_type'] = fields['target_type'].value
```

2021-05-01 18:06 UTC, Rapptz commented on discord/invite.py
> +        application = data.get("target_application")
```suggestion
        application = data.get('target_application')
```

2021-05-01 18:06 UTC, Rapptz commented on discord/types/appinfo.py
> +"""
Something about the way these types are duplicated here doesn't sit well with me. Is there no way to reduce the duplication here? The types should mirror this one: <https://discord.com/developers/docs/topics/oauth2#application>

2021-05-29 04:15 UTC, Rapptz approved these changes

2021-05-29 04:15 UTC, merged