Type-Hint http.py
Rapptz/discord.py pull request #6882
Opened 2021-05-09 15:58 UTC by bijij

## Summary

**This PR is not completed.**

This PR starts the ground-work for type-hinting http.py

In it's current state it relies on #6871 and #6872 for http payload typings.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-06-08 12:44 UTC, NCPlayz requested changes
just skimmed over the typings, seems alright

2021-06-09 11:48 UTC, AbstractUmbra reviewed
A few annotation skips.

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +    def edit_my_voice_state(self, guild_id: Snowflake, payload) -> Response[None]:
`payload` param should be annotated.

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +    def edit_voice_state(self, guild_id: Snowflake, user_id: Snowflake, payload) -> Response[None]:
`payload` param should be annotated.

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        data,
`data` param should be annotated.

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        self, channel_id: Snowflake, before=None, limit: int = 50
`before` should perhaps be annotated even if unused?

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        self, channel_id: Snowflake, before=None, limit: int = 50
`before` should perhaps be annotated even if unused?

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        self, channel_id: Snowflake, before=None, limit: int = 50
`before` should perhaps be annotated even if unused?

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +    def create_template(self, guild_id: Snowflake, payload) -> Response[template.Template]:
`payload` param should be annotated.

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        payload,
`payload` param should be annotated?

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        payload,
`payload` param should be annotated?

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        payload,
`payload` param should be annotated?

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        payload,
`payload` param should be annotated.

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        payload,
`payload` param should be annotated.

2021-06-09 11:48 UTC, AbstractUmbra commented on discord/http.py
> +        payload
`payload` param should be annotated.

2021-06-09 12:20 UTC, Rapptz requested changes

2021-06-09 12:20 UTC, Rapptz commented on discord/http.py
> +    def delete_messages(self, channel_id: Snowflake, message_ids: List[int], *, reason: Optional[str] = None) -> Response[None]:
```suggestion
    def delete_messages(self, channel_id: Snowflake, message_ids: List[Snowflake], *, reason: Optional[str] = None) -> Response[None]:
```

2021-06-09 12:20 UTC, Rapptz commented on discord/http.py
> +        roles: Optional[List[int]] = None,
```suggestion
        roles: Optional[List[Snowflake]] = None,
```

2021-06-09 12:20 UTC, Rapptz commented on discord/http.py
> +        payload,
```suggestion
        payload: Dict[str, Any],
```

2021-06-09 12:20 UTC, Rapptz commented on discord/http.py
> +        positions,
```suggestion
        positions: List[Dict[str, Any]],
```

2021-06-09 12:20 UTC, Rapptz commented on discord/http.py
> +        role_ids: List[int],
```suggestion
        role_ids: List[Snowflake],
```

2021-06-09 13:18 UTC, ToxicKidz requested changes

2021-06-09 13:18 UTC, ToxicKidz commented on discord/http.py
> +        traceback: TracebackType,
```suggestion
        traceback: Optional[TracebackType],
```

2021-06-09 13:18 UTC, ToxicKidz commented on discord/http.py
> +        form: Iterable[Dict[str, Any]] = None,
```suggestion
        form: Optional[Iterable[Dict[str, Any]]] = None,
```

2021-06-09 13:18 UTC, ToxicKidz commented on discord/http.py
> +        message_reference: Optional[Snowflake] = None,
Isn't `message_reference` a dict?
```suggestion
        message_reference: Optional[message.MessageReference] = None,
```

2021-06-09 13:18 UTC, ToxicKidz commented on discord/http.py
> +        after=None,
```suggestion
        after: Optional[Snowflake] = None,
```

2021-06-10 11:34 UTC, Rapptz approved these changes

2021-06-10 11:34 UTC, merged