Add support for editing guild widgets
Rapptz/discord.py pull request #7004
Opened 2021-06-01 21:44 UTC by MhmCats

## Summary

This pull requests adds support for editing guild widgets.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-06-01 22:00 UTC, Zomatree commented on discord/guild.py
> +    async def edit_widget(self, *, enabled: bool, channel: abc.Snowflake) -> None:
Both parameters should be optional, also channel can be set to none.

2021-06-01 22:09 UTC, SebbyLaw requested changes

2021-06-01 22:09 UTC, SebbyLaw commented on discord/guild.py
> +            Whether to enabled the widget for the guild.
```suggestion
            Whether to enable the widget for the guild.
```

2021-06-02 06:33 UTC, Rapptz requested changes
This is inconsistent with the rest of the library.

2021-06-02 06:33 UTC, Rapptz commented on discord/guild.py
> +    async def edit_widget(self, *, enabled: bool = None, channel: abc.Snowflake = None) -> None:
```suggestion
    async def edit_widget(self, *, enabled: bool = utils.MISSING, channel: Optional[abc.Snowflake] = utils.MISSING) -> None:
```

2021-06-02 06:33 UTC, Rapptz commented on discord/guild.py
> +            The widget channel.
```suggestion
        channel: Optional[:class:`~discord.abc.Snowflake`]
            The new widget channel. ``None`` removes the widget channel.
```

2021-06-02 06:33 UTC, Rapptz commented on discord/guild.py
> +        await self._state.http.edit_widget(self.id, enabled=enabled, channel_id=channel)
```suggestion
        payload = {}
        if channel is not utils.MISSING:
            payload['channel_id'] = None if channel is None else channel.id
        if enabled is not utils.MISSING:
            payload['enabled'] = enabled

        await self._state.http.edit_widget(self.id, payload=payload)
```

2021-06-02 06:33 UTC, Rapptz commented on discord/http.py
> +    def edit_widget(self, guild_id, **payload):
```suggestion
    def edit_widget(self, guild_id, payload):
```

2021-06-02 06:39 UTC, merged