add Guild.nsfw_level
Rapptz/discord.py pull request #7012
Opened 2021-06-03 19:51 UTC by NCPlayz

## Summary

discord/discord-api-docs@445832c

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-06-03 21:12 UTC, Ti7oyan approved these changes

2021-06-07 07:30 UTC, Rapptz requested changes

2021-06-07 07:30 UTC, Rapptz commented on discord/guild.py
> +        self.nsfw_level = try_enum(NSFWLevel, guild.get('nsfw_level'))
```suggestion
        self.nsfw_level = try_enum(NSFWLevel, guild.get('nsfw_level', 0))
```

2021-06-07 07:30 UTC, Rapptz commented on discord/types/guild.py
>      nsfw: bool
```suggestion
```

This apparently got removed. The guild property will need to get removed as well.

2021-06-08 03:19 UTC, Rapptz approved these changes

2021-06-08 03:20 UTC, merged