implement guild stickers
Rapptz/discord.py pull request #7126
Opened 2021-06-29 00:25 UTC by NCPlayz

## Summary

discord/discord-api-docs#3128

WIP. Would hugely appreciate testing this PR.

Features remaining to implement:
- [ ] Client.fetch_sticker
- [ ] Client.stickers
- [ ] Client.get_sticker
- [ ] Client.standard_sticker_packs (Name pending?)
- [ ] StickerPack
- [ ] Sticker Pack Banner Asset

Also TODO:
- [ ] Re-document StickerFormatType
- [ ] Document StickerType
- [ ] Document every other dataclass.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-07-20 23:49 UTC, oliver-ni commented on discord/abc.py
> +        if stickers:
```suggestion
        if stickers is not None:
```

To stay consistent with the rest of the library, I think? At least, the rest of this method.

2021-07-20 23:49 UTC, oliver-ni commented on discord/guild.py
> +        Creates a :class:`Sticker`s for the guild.
```suggestion
        Creates a :class:`Sticker` for the guild.
```

Hehe. Maybe also want to specify "custom"?

2021-07-20 23:49 UTC, oliver-ni commented on discord/http.py
> +        stickers: Optional[List[sticker.StickerItem]] = None,
Not familiar with typing. Is there a reason it's typed `Optional` here and not in `abc.Messageable.send`? Noticed many other attributes not typed as `Optional` there as well.

2021-07-20 23:49 UTC, oliver-ni commented on discord/sticker.py
> +        Creates a :class:`Sticker` for the guild.
Wrong doc?

2021-07-21 00:15 UTC, ToxicKidz requested changes

2021-07-21 00:15 UTC, ToxicKidz commented on discord/client.py
> +        """Returns a guild emoji with the given ID.
```suggestion
        """Returns a guild sticker with the given ID.
```

2021-07-21 00:15 UTC, ToxicKidz commented on discord/client.py
> +    async def fetch_sticker(self, sticker_id: int) -> Union[StandardSticker, GuildSticker]:
Are these missing version addeds?

2021-07-21 14:22 UTC, Daggy1234 requested changes
These were just some docfixes I had noticed

2021-07-21 14:22 UTC, Daggy1234 commented on discord/sticker.py
> +        The format for the sticker's image.
Shouldn't `url` be in this docstring

2021-07-21 14:22 UTC, Daggy1234 commented on discord/sticker.py
> +        The URL for the sticker's image.
tags should be in the docstring

2021-07-21 21:16 UTC, LostLuma commented on discord/guild.py
> +        self.stickers: Tuple[Emoji, ...] = tuple(map(lambda d: state.store_sticker(self, d), guild.get('stickers', [])))
```suggestion
        self.stickers: Tuple[GuildSticker, ...] = tuple(map(lambda d: state.store_sticker(self, d), guild.get('stickers', [])))
```

2021-07-21 21:16 UTC, LostLuma commented on discord/client.py
> +        Optional[:class:`.Sticker`]
```suggestion
        Optional[:class:`.GuildSticker`]
```

2021-07-21 21:16 UTC, LostLuma commented on discord/guild.py
> +        List[:class:`Sticker`]
```suggestion
        List[:class:`GuildSticker`]
```

2021-07-21 21:16 UTC, LostLuma commented on discord/guild.py
> +        :class:`Sticker`
```suggestion
        :class:`GuildSticker`
```

2021-07-21 21:16 UTC, LostLuma commented on discord/guild.py
> +        :class:`Sticker`
```suggestion
        :class:`GuildSticker`
```

2021-07-21 21:16 UTC, LostLuma commented on discord/guild.py
> +            The emoji you are deleting.
```suggestion
            The sticker you are deleting.
```

2021-07-21 21:39 UTC, diceroll123 commented on discord/client.py
> +    def get_sticker(self, id) -> Optional[GuildSticker]:
```suggestion
    def get_sticker(self, id: int) -> Optional[GuildSticker]:
```

2021-07-28 23:50 UTC, Rapptz requested changes
This PR is good.

I think type annotations should be used for all variable declarations within `__init__` though since we're doing that going forward for meeting pyright's typed % metric. i.e.
```py
def __init__(self, foo: int):
    self.foo: int = foo
```

even though it's repetitive

2021-07-28 23:50 UTC, Rapptz commented on discord/guild.py
> +        None: _GuildLimit(emoji=50, stickers=15, bitrate=96e3, filesize=8388608),
```suggestion
        None: _GuildLimit(emoji=50, stickers=0, bitrate=96e3, filesize=8388608),
```

2021-07-28 23:50 UTC, Rapptz commented on discord/sticker.py
> +        'banner',
One of these should be a property

2021-07-31 01:25 UTC, Rapptz approved these changes

2021-07-31 01:25 UTC, merged