add types to thread channels
Rapptz/discord.py pull request #7142
Opened 2021-07-01 00:34 UTC by applebee1558

## Summary

It adds back the type property into threads, as it was missing, but all other channels contain it.
## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-07-01 11:51 UTC, Rapptz requested changes
Implementation could be simpler.

2021-07-01 11:51 UTC, Rapptz commented on discord/threads.py
> +        self._type = data['type']
Revert this.

2021-07-01 11:51 UTC, Rapptz commented on discord/threads.py
> +        return self.type is ChannelType.private_thread
Revert this.

2021-07-01 11:51 UTC, Rapptz commented on discord/threads.py
> +        return self.type is ChannelType.news_thread
Revert this.

2021-07-01 11:51 UTC, Rapptz commented on discord/threads.py
> +        return try_enum(ChannelType, self._type)
```suggestion
        return self._type
```

2021-07-01 14:26 UTC, applebee1558 commented
Ok, I’ve done the changes you requested for.

2021-07-02 00:27 UTC, Rapptz approved these changes
Thanks.

2021-07-02 00:27 UTC, merged