[commands] update clean_content to work when standalone
Rapptz/discord.py pull request #7174
Opened 2021-07-05 05:21 UTC by z03h

## Summary

Changes clean_content converter to not use `ctx.message.raw_mentions`/`role_mentions` so it gives more expected results when used standalone outside of command conversion. Also fixes bug where specifying `use_nicknames=False` could resolve users outside of the current guild.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-07-05 05:28 UTC, Rapptz commented
Was it necessary to rewrite the entire function for this supposed bug fix? `clean_content` used those attributes by design because the `mentions` field requires the users to actually be in the mention regardless of `allowed_mentions`. The point of the function is to clean *all* mentions, even potential ones that are ignored from `allowed_mentions`. Likewise, `role_mentions` field requires role cache and has the same gotchas as the one I mentioned for users. I see no real reason to change the attributes.

2021-07-05 05:33 UTC, z03h commented
The rewrite was to make it searches arg for mentions instead of only replacing mentions that are in ctx.message.content.
Intention was to add ability to clean mentions if you use it outside of type hints like `await clean_content().convert(ctx, random_string)`. Unless that's an unintended use for converters?

2021-07-05 05:44 UTC, Rapptz requested changes
Overall this is missing type hints. This also doesn't match the style of the rest of the library.

2021-07-05 05:44 UTC, Rapptz commented on discord/ext/commands/converter.py
> +        pattern = re.compile(r'<(@[!&]?|#)(\d{15,20})>')
```suggestion
        pattern = re.compile(r'<(@[!&]?|#)([0-9]{15,20})>')
```

If this compilation isn't stored then it's pointless, the `re` module already caches recently used regex.

2021-07-05 05:44 UTC, Rapptz commented on discord/ext/commands/converter.py
> +                      }
```suggestion
        transforms = {
            '@': resolve_member,
            '@!': resolve_member,
            '#': resolve_channel,
            '@&': resolve_role,
        }
```

2021-07-05 05:44 UTC, Rapptz commented on discord/ext/commands/converter.py
> +                 remove_markdown: bool = False) -> None:
```suggestion
    def __init__(
        self,
        *,
        fix_channel_mentions: bool = False,
        use_nicknames: bool = True,
        escape_markdown: bool = False,
        remove_markdown: bool = False,
    ) -> None:
```

2021-07-05 05:44 UTC, Rapptz commented on discord/ext/commands/converter.py
> +    async def convert(self, ctx, arg):
```suggestion
    async def convert(self, ctx: Context, argument: str) -> str:
```

Changing this signature made no sense.

2021-07-05 05:54 UTC, z03h commented
🙃 I'm dented

2021-07-05 05:56 UTC, Rapptz requested changes
Type hints are still missing but it's fine it can be dealt with afterwards if you're not familiar with it.

2021-07-05 05:56 UTC, Rapptz commented on discord/ext/commands/converter.py
> +    async def convert(self, ctx: Context, arg: str) -> str:
```suggestion
    async def convert(self, ctx: Context, argument: str) -> str:
```

Parameter names are part of the API contract, you can't change them.

2021-07-05 05:59 UTC, z03h commented
ah I missed that, and type hinting all the `resolve_x`?

2021-07-05 06:04 UTC, Rapptz commented
If you're not familiar with it it's fine.

2021-07-05 06:43 UTC, z03h commented
I think that's it, not sure if I missed something

2021-07-08 00:15 UTC, Rapptz approved these changes

2021-07-08 00:15 UTC, merged