Add a new view example for link buttons
Rapptz/discord.py pull request #7189
Opened 2021-07-07 23:01 UTC by Ay-355

## Summary

This PR adds a new view example showcasing how to create a link button.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-07-08 00:18 UTC, Rapptz commented
I don't really think this is a good example of a link button. Also, this constructor got simplified so someone doesn't have to do it this way.

2021-07-09 02:21 UTC, Ay-355 commented
Are there any other examples of a link button that would be a better fit for the repo, or is the example not needed?

2021-07-21 07:05 UTC, Rapptz requested changes

2021-07-21 07:05 UTC, Rapptz commented on examples/views/link.py
> +        self.query = query.replace(' ', '+')
No, you want to use [`urllib.parse.quote_plus`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus). Be sure to import it at the top as `from urllib.parse import quote_plus`.

```suggestion
        # we need to quote the query string to make a valid url. Discord will raise an error if it isn't valid.
        query = quote_plus(query)
        url = f'https://www.google.com/search?q={query}'
```

2021-07-21 07:05 UTC, Rapptz commented on examples/views/link.py
> +        )
The construction could be severely simplified.

```suggestion
        self.add_item(discord.ui.Button(label='Click Here', url=url))
```

2021-07-22 14:01 UTC, Rapptz approved these changes
Thanks.

2021-07-22 14:02 UTC, Rapptz commented on examples/views/link.py
> +    await ctx.send(f"Google Result for: `{query}`", view=Google(query))
```suggestion
    await ctx.send(f'Google Result for: `{query}`', view=Google(query))
```

2021-07-22 14:02 UTC, merged