Added pagination example with buttons
Rapptz/discord.py pull request #7234
Opened 2021-07-14 15:44 UTC by Prince2347X

## Summary

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [X] This PR is **not** a code change (e.g. documentation, README, ...)

2021-07-14 15:49 UTC, Phxntxm requested changes

2021-07-14 15:49 UTC, Phxntxm commented on examples/views/pagination.py
> +    current = 0 # It's not in the constructor because it'll be reset everytime the view is updated.
No it wouldn't? If it would, so would the `embed_list`

2021-07-14 15:49 UTC, Phxntxm commented on examples/views/pagination.py
> +    async def previous(self, button, interaction):
Why are some things type hinted, but some aren't

2021-07-14 15:49 UTC, Phxntxm commented on examples/views/pagination.py
> +        self.next.disabled = False
Why is this here? Is this implying that `embed_list` can be modified and next should be updated to reflect that? If so, then there is no handling of to disabling the button later

2021-07-14 15:49 UTC, Phxntxm commented on examples/views/pagination.py
> +            await interaction.response.edit_message(embed=self.embed_list[self.current], view=self)
In general, this is nearly the same exact thing as `previous`. This should really be moved into a function that handles updating information

2021-07-15 02:52 UTC, Prince2347X commented
Noted.

2021-07-21 06:54 UTC, Rapptz commented
Sorry, this example doesn't match the style and quality of the pre-existing examples.

2021-07-21 06:54 UTC, closed without merging