Removes any references encouraging users to write their token directly in their bot code.
Rapptz/discord.py pull request #7272
Opened 2021-07-23 18:34 UTC by timothypidashev

## Summary

PR for issue: https://github.com/Rapptz/discord.py/issues/2518
Removes any references encouraging users to write their token directly in their bot code. 

```python
with open('token.txt') as f:
      token = f.read()

client.run(token) #or bot when in context
```

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-07-23 18:37 UTC, lgaan commented
I don’t think this is really needed.

The examples are there to provide a basic, one-file approach to basic concepts in the library; nowhere in the examples folder is a reference to loading tokens from separate files nor does this file exist leading to potentially more confusion.

Of course my say isn’t final, but this is just what I think.

2021-07-23 18:49 UTC, JelNiSlaw commented
I think reading an environment variable would be a better solution

2021-07-23 19:51 UTC, timothypidashev commented
I dont exactly think this is needed as well, but im just doing my part to clean up the issues page

2021-07-23 19:56 UTC, Phxntxm commented
> I think reading an environment variable would be a better solution

I do not, I've seen far too many times where people come from these service that use `.env` file as a standard to import env variables. They then think that's normal, they have to do nothing and the file is magically loaded which is NOT the case in normal environments. I would prefer something that is an example to do something like this, reading from a file, where it's more direct what is happening.

Using environment variables then means you have to teach the user how to actually *create* environment variables, expanding the scope of this. Putting some text in a file is something you do not have to teach

2021-07-23 20:01 UTC, apple502j commented
I'd say we should use `.env` and mention `python-dotenv`.

2021-07-23 20:02 UTC, Phxntxm commented
> I'd say we should use `.env` and mention `python-dotenv`.

I VERY STRONGLY disagree with this, due to the first part I mentioned in my first reply. I have seen way too many people be bit by this from heroku/replit to support this

2021-07-23 20:03 UTC, lgaan commented
> I'd say we should use `.env` and mention `python-dotenv`.

Back to my previous point, examples are meant to not rely on external packages.

2021-07-23 20:03 UTC, timothypidashev commented
> Using environment variables then means you have to teach the user how to actually _create_ environment variables, expanding the scope of this. Putting some text in a file is something you do not have to teach

I agree with @Phxntxm. Enlarging the scope of this is the worst path to take in this situation. We simply don't want to promote hard-coding tokens into files that will most likely make it onto a repository later

2021-07-26 00:53 UTC, ioistired requested changes

2021-07-26 00:53 UTC, ioistired commented on examples/views/link.py
> +bot.run(token)
mising newline at EOF

2021-07-26 00:53 UTC, ioistired commented on examples/views/persistent.py
> +bot.run(token)
missing a newline at EOF here too

2021-07-26 17:37 UTC, timothypidashev commented on examples/views/link.py
> +bot.run(token)
will push in a sec

2021-07-26 17:39 UTC, timothypidashev commented on examples/views/persistent.py
> +bot.run(token)
done

2021-07-29 02:07 UTC, ImportTaste commented
If this isn't approved, at the very least, there should be a comment in the example files warning users never to share any file that has their token inside of it right above the line where they put their token in.

2021-08-02 15:45 UTC, timothypidashev commented
> If this isn't approved, at the very least, there should be a comment in the example files warning users never to share any file that has their token inside of it right above the line where they put their token in.

agree

2021-08-03 07:29 UTC, Hyperclaw79 commented
Discord itself warns us while creating the token....I personally don't think there's a need to again tell people to not hard-code the token. It's something that should be pretty obvious....

2021-08-03 08:39 UTC, oliver-ni commented
> Discord itself warns us while creating the token....I personally don't think there's a need to again tell people to not hard-code the token. It's something that should be pretty obvious....

They don't, actually.

2021-08-03 13:07 UTC, Hyperclaw79 commented
> They don't, actually.

oh....you're right. For some reason, I remember seeing a warning when we click on Copy/Reveal. Guess I confused it with some other app.
Either way, that warning should be provided by Discord itself, rather than a library.

2021-08-03 17:40 UTC, timothypidashev commented
> Either way, that warning should be provided by Discord itself, rather than a library.
I agree Discord itself should provide a warning, but discord.py is not out of the picture either, and implying hard-coding tokens all throughout the docs and examples is not going to benefit anyone, in my humble opinion.

2021-08-17 15:50 UTC, timothypidashev commented
The only inconsistency I can think of atm for this pr is the use of both `bot` and `client` when setting up the bot class. Should I make changes(switch all to client or bot), or keep as is?

2021-08-18 19:56 UTC, ioistired commented
It's consistent with the fact that all instances of `commands.Bot` are called `bot` and all instances of `discord.Client` are called `client`, so keep it as is.

2021-08-18 23:51 UTC, timothypidashev commented
> It's consistent with the fact that all instances of `commands.Bot` are called `bot` and all instances of `discord.Client` are called `client`, so keep it as is.

That is a good point, I will keep as is, thank you for pointing this out!

2022-04-19 14:50 UTC, timmypidashev commented
Closing this pull request as it is stale and not relevant to current development.

2022-04-19 14:50 UTC, closed without merging