Update converter.py
Rapptz/discord.py pull request #7312
Opened 2021-07-31 11:54 UTC by Daggy1234

## Summary

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-07-31 11:59 UTC, Daggy1234 commented
Extremely sorry for the lack of a description. Clicked on the create button by mistake while adding the description.

2021-07-31 12:06 UTC, JelNiSlaw commented
I think `re.fullmatch` should be used instead of `re.match`. That would make `$` unnecessary.
Also the rest of the library's code uses `[0-9]` instead of `\d` (I'm not sure why).

2021-07-31 12:10 UTC, JelNiSlaw commented on discord/ext/commands/converter.py
> +            except:
You shouldn't be using a bare except

2021-07-31 12:19 UTC, apple502j commented
> Also the rest of the library's code uses `[0-9]` instead of `\d` (I'm not sure why).

Because:
```py
>>> match(r"^\d+$","٠1１")
<re.Match object; span=(0, 3), match='٠1１'>
```

2021-07-31 12:22 UTC, NCPlayz requested changes
I feel like this would be better if it was a utility function rather than a converter. Something along the lines of `resolve_formatted_timestamp` maybe. It doesn't seem right for the programmer to need to access the converter directly to use as the annotation, and it seems unlikely that a user would be sending a formatted timestamp (over natural language) to specify a date/time argument for a command anyway. 

Just my two cents!

2021-08-01 11:27 UTC, Daggy1234 commented
So I added the util, but I still kept the converter. The converter also uses the util, and my basic reasoning for retaining the converter was that  eventually discord would add a way for users to send these. Also moved the regex to use [0-9] and added a time zone to the datetime.

2021-08-01 11:28 UTC, Gobot1234 commented on discord/utils.py
> +        except:
You're using a bare except again

2021-08-01 11:29 UTC, Gobot1234 commented on discord/utils.py
> +    return
This is unnecessary

2021-08-01 11:36 UTC, Daggy1234 commented
In terms of exceptions, for the `int` cast a ValueError, datetime.datetime.fromtimestamp can either raise an OverflowError or a OSError. Both are handled as well. https://docs.python.org/3/library/datetime.html#datetime.date.fromtimestamp

2021-08-01 13:57 UTC, JelNiSlaw commented
Is it possible for `int` to raise `ValueError` here?

2021-08-01 16:34 UTC, Daggy1234 commented
> Is it possible for `int` to raise `ValueError` here?

if the regex works probably not. The `int` is for pyright that was complaining a lot.

2021-08-21 00:17 UTC, Rapptz commented
I'm personally not sure I get the utility of this one. Users aren't necessarily aware of this format at the moment and having to type it manually seems like a chore.

2021-08-21 07:24 UTC, Daggy1234 commented
Yeah! hence, the utility. Developers can use the utility to parse the timestamps from content bots may send, like editing a timestamp field in an embed. The converter is auxiliary, I can totally remove it, but if discord were to add the ability to send timestamps it exists.

2022-03-11 01:58 UTC, closed without merging