Make enums comparable
Rapptz/discord.py pull request #7413
Opened 2021-08-19 01:11 UTC by SebbyLaw

## Summary

Add comparison operations to Enum. Also added docs for supported operations on some enums where comparing values might be relevant.

Not sure what to do about the supported operations containers on VerificationLevel and ContentFilter that were added in #688 and then broken in 0ddc6867e9e2c98d74a4ef85ac36a99fec5a1f03.

This PR closes #7250.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-08-19 23:59 UTC, Rapptz requested changes
I think it's better to make this opt-in rather than being unconditional as it is now. A lot of enums are strings and string comparisons are useless. This should really only be done for numerical, documented, enums.

2021-08-24 05:14 UTC, SebbyLaw commented
> Not sure what to do about the supported operations containers on VerificationLevel and ContentFilter that were added in #688 and then broken in 0ddc6867e9e2c98d74a4ef85ac36a99fec5a1f03.

Should these have a versionadded as well?

2021-08-24 05:23 UTC, Rapptz requested changes
The docs should be updated to reflect the changes.

2021-08-24 05:23 UTC, Rapptz commented on discord/enums.py
> +    def __new__(cls, name, bases, attrs, **kwargs):
```suggestion
    def __new__(cls, name, bases, attrs, *, comparable: bool = False):
```

2021-08-24 05:23 UTC, Rapptz commented on discord/enums.py
> +            value_cls.__gt__ = lambda self, other: isinstance(other, self.__class__) and self.value > other.value
Move this to `_create_value_cls`. This stuff was in that function to prevent the unnecessary closure.

2021-08-24 06:28 UTC, Rapptz approved these changes

2021-08-24 06:28 UTC, merged