Add missing type: ignore and missing typehint to channel.py
Rapptz/discord.py pull request #7450
Opened 2021-08-22 15:35 UTC by StockerMC

## Summary

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2021-08-22 15:36 UTC, StockerMC commented
Should the signature of `store_user` and `User` be changed to accept a union of `PartialUserPayload` and `UserPayload`?

2021-08-23 09:20 UTC, Rapptz requested changes

2021-08-23 09:20 UTC, Rapptz commented on discord/channel.py
> +        self.recipient: Optional[User] = state.store_user(data['recipients'][0]) # type: ignore
I'm not going to accept this type ignore.

2021-08-24 01:03 UTC, Rapptz approved these changes
Thanks.

2021-08-24 01:03 UTC, merged