Add som missing typehints for `get_*` methods in client.py
Rapptz/discord.py pull request #7455
Opened 2021-08-22 20:58 UTC by MrKomodoDragon

## Summary

This PR adds the missing typehints for the `id` parameter in some of the `get_*` methods for the `Client` class in client.py

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-08-22 21:01 UTC, NCPlayz requested changes
These should all have positional only indicators too.

2021-08-23 09:28 UTC, Rapptz commented on discord/client.py
> +    def get_stage_instance(self, id: int) -> Optional[StageInstance]:
```suggestion
    def get_stage_instance(self, id: int, /) -> Optional[StageInstance]:
```

2021-08-23 09:28 UTC, Rapptz commented on discord/client.py
> +    def get_guild(self, id: int) -> Optional[Guild]:
```suggestion
    def get_guild(self, id: int, /) -> Optional[Guild]:
```

2021-08-23 09:28 UTC, Rapptz commented on discord/client.py
> +    def get_user(self, id: int) -> Optional[User]:
```suggestion
    def get_user(self, id: int, /) -> Optional[User]:
```

2021-08-23 09:28 UTC, Rapptz commented on discord/client.py
> +    def get_emoji(self, id: int) -> Optional[Emoji]:
```suggestion
    def get_emoji(self, id: int, /) -> Optional[Emoji]:
```

2021-08-23 09:28 UTC, merged