Make `Guild.member_count` Optional
Rapptz/discord.py pull request #7605
Opened 2022-03-09 08:31 UTC by AbstractUmbra

## Summary

According to multiple reports, this key is not always present in a guild payload. Currently the library only sets this attribute if it is not `None` resulting in a rare error during startup or when retrieving guilds.
Potentially a fix for #6652?

I have made this attribute and property `Optional` as a result, to avoid an `AttributeError`.

Sadly I cannot test this, due to potentially requiring an "unavailable" guild.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-03-09 12:41 UTC, Rapptz commented
I don't know how I feel about the type of `member_count` changing to `Optional[int]`. Python ergonomics with optional types is subpar, especially when the data is always there. Not sure what the solution is but it is unfortunate.

2022-03-09 23:23 UTC, dolfies commented
Unless I'm misremembering, the only time `member_count` will not be present is when a guild is unavailable. In that case, can't we just default to 0? ~~You could argue it actually is 0 since no-one can access it.~~

2022-03-09 23:32 UTC, EvieePy commented
I don't think 0 makes a lot of sense here. The guild member count is still above 0, regardless of whether it is unavailable or not.
If you were going to return 0 you might as well just return None for some sanity. But I'm not sure... So goodlock with this.

2022-03-10 02:09 UTC, dolfies commented
None will make typing UX not amazing.

2022-03-10 02:12 UTC, AbstractUmbra commented
I am aware that marking this attribute as `Optional` is a far from ideal solution, however I believe that it's the lesser of two evils, considering the other option (at the moment) is a rare AttributeError that's been affecting people.

I'd rather a little extra work to appease a type checker than it just dying, personally.

2022-03-10 02:19 UTC, Rapptz requested changes
Needs updating migrating.rst

2022-03-10 02:19 UTC, Rapptz commented on discord/guild.py
> +
Extra newline.
```suggestion
```

2022-03-10 04:03 UTC, dolfies commented
> I am aware that marking this attribute as `Optional` is a far from ideal solution, however I believe that it's the lesser of two evils, considering the other option (at the moment) is a rare AttributeError that's been affecting people.
> 
> I'd rather a little extra work to appease a type checker than it just dying, personally.

That's why 0 is a good middle ground.

2022-03-10 04:05 UTC, Rapptz approved these changes

2022-03-10 04:06 UTC, merged