Add `jump_url` property to Channels
Rapptz/discord.py pull request #7867
Opened 2022-04-10 14:17 UTC by Pysics

## Summary

- `TextChannel`
- `VoiceChannel`
- `StageChannel`

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-04-10 14:32 UTC, LostLuma commented
This is missing the property on `ForumChannel`, although I'm unsure this will be merged as the feature has been denied previously (see #2355).

2022-04-10 15:53 UTC, Vioshim commented
> This is missing the property on `ForumChannel`, although I'm unsure this will be merged as the feature has been denied previously (see #2355).

To be fair, back then we didn't have discord components, this jump_url feature in channels would be very useful to redirect users through URL Buttons in views.

2022-04-10 15:54 UTC, Gobot1234 commented
This is also missing support for DMChannel is it not?

2022-04-10 16:12 UTC, Pysics commented
For now, I have made this PR a draft.
I will look into implementing more features tomorrow.

2022-04-10 17:10 UTC, dolfies commented
> This is missing the property on `ForumChannel`, although I'm unsure this will be merged as the feature has been denied previously (see #2355).

Copy link is an option in the client's context menu now, so it isn't a "hack" anymore.

2022-04-11 04:06 UTC, Pysics commented
I have added more support and this PR is ready for review.

2022-04-11 21:23 UTC, Rapptz requested changes
Rather than copying this implementation everywhere in every guild channel type you probably want to do it inside abc.GuildChannel.

2022-04-11 21:23 UTC, Rapptz commented on discord/channel.py
> +        .. versionadded:: 2.0
These need a newline between them.

```suggestion

        .. versionadded:: 2.0
```

2022-04-12 02:45 UTC, Pysics commented
I have not added support for `CategoryChannel`.
So, I can't add the `jump_url` property to `abc.GuildChannel`.

2022-04-12 02:49 UTC, Rapptz commented
> I have not added support for `CategoryChannel`. So, I can't add the `jump_url` property to `abc.GuildChannel`.

I'd rather it be in all channels than duplicate all of this. Plus, this would play better with type checkers.

2022-04-12 03:43 UTC, Pysics commented
@Rapptz I have made the requested changes.

2022-04-12 03:48 UTC, Rapptz commented
This is failing type checking.

You don't want to add this jump_url property to the abc.PrivateChannel protocol. That one will have to be done manually to the things that meet the protocol since it isn't an actual runtime base class.

2022-04-12 03:48 UTC, Rapptz requested changes
Needs to fix type checking concern.

2022-04-12 04:22 UTC, Rapptz approved these changes
Thanks. LGTM.

2022-04-12 04:23 UTC, merged