News Channel Support
Rapptz/discord.py pull request #7953
Opened 2022-04-29 14:14 UTC by FrostiiWeeb

## Summary

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-04-29 14:27 UTC, bijij requested changes

2022-04-29 14:27 UTC, bijij commented on discord/guild.py
> +        news: bool = MISSING,
This could just default to `False`
```suggestion
        news: bool = False,
```

2022-04-29 17:06 UTC, Rapptz requested changes
This needs documentation.

2022-04-30 07:38 UTC, Rapptz commented on discord/guild.py
> +            Whether to mark the channel as a news channel or not.
```suggestion
        news: :class:`bool`
            Whether to create the text channel as a news channel.

            .. versionadded:: 2.0
```

2022-04-30 09:41 UTC, Rapptz requested changes
This is failing CI due to a type check error.

Chances are, you need an overload in `_create_channel` handle the union of the two literal types being passed in.

2022-04-30 11:05 UTC, Rapptz commented
Closing per request.

2022-04-30 11:05 UTC, closed without merging