Use static_format over format if not MISSING
Rapptz/discord.py pull request #8104
Opened 2022-06-03 19:32 UTC by Soheab

## Summary

Fixes #7345 and resolved [card-81287372](https://github.com/Rapptz/discord.py/projects/3#card-81287372)

This PR uses `static_format` if `format` is not in VALID_STATIC_FORMATS and static_format is.
Not sure if this is the right way to do this.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-06 03:07 UTC, ajsharda17 approved these changes

2022-06-08 23:41 UTC, Rapptz requested changes
I think since the `static_format` branch will run regardless, it might make sense to delay the error checking?

Ergo, change the original raising condition from `if format not in VALID_STATIC_FORMATS` to `if static_format is MISSING and format not in VALID_STATIC_FORMATS`.

2022-06-09 17:24 UTC, Soheab commented
> I think since the `static_format` branch will run regardless, it might make sense to delay the error checking?
> 
> Ergo, change the original raising condition from `if format not in VALID_STATIC_FORMATS` to `if static_format is MISSING and format not in VALID_STATIC_FORMATS`.

Yep, that works nicely.

2022-06-10 05:49 UTC, Rapptz approved these changes
Thanks.

2022-06-10 05:50 UTC, merged