add a richer type for `Message.application`
Rapptz/discord.py pull request #8127
Opened 2022-06-09 03:51 UTC by AbstractUmbra

## Summary

This PR adds `MessageApplication` as a richer type for `Message.application`.

It also adds a new classmethod to `Asset` for getting app-icons cdn contents.
The `.icon` and `.cover_image` properties have not been tested currently, but have followed the API docs and payload types.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-09 04:59 UTC, Rapptz requested changes
Needs to be documented in the migrating.rst file

2022-06-09 04:59 UTC, Rapptz commented on discord/message.py
> +    application: Optional[:class:`~discord.MessageApplication`]
Needs a versionchanged

2022-06-09 04:59 UTC, Rapptz commented on discord/message.py
> +    .. versionadded:: 2.0
This belongs before Attributes

2022-06-09 04:59 UTC, Rapptz commented on discord/message.py
> +    )
I think these are small enough to be compacted into one line.

2022-06-09 04:59 UTC, Rapptz commented on discord/message.py
> +        return f"<MessageApplication id={self.id} name={self.name!r}>"
```suggestion
        return f'<MessageApplication id={self.id} name={self.name!r}>'
```

2022-06-09 04:59 UTC, Rapptz commented on discord/message.py
> +            return Asset._from_app_icon(state=self._state, object_id=self.id, icon_hash=self._icon, asset_type='icon')
Please add an explicit None return.

2022-06-09 04:59 UTC, Rapptz commented on discord/message.py
> +            )
Please add an explicit None return.

2022-06-12 02:46 UTC, NCPlayz requested changes

2022-06-12 02:46 UTC, NCPlayz commented on discord/asset.py
> +    def _from_app_icon(cls, state: _State, object_id: int, icon_hash: str, asset_type: Literal['icon', 'cover_image']):
```suggestion
    def _from_app_icon(cls, state: _State, object_id: int, icon_hash: str, asset_type: Literal['icon', 'cover_image']) -> Self
```

2022-06-13 20:31 UTC, Rapptz approved these changes

2022-06-13 20:31 UTC, Rapptz commented on discord/message.py
> +            This now returns a richer interface type, not a `dict` of the raw payload.
```suggestion
            Type is now :class:`MessageApplication` instead of :class:`dict`.
```

2022-06-13 20:34 UTC, merged