Make `app_commands.Command` and others comparable with `AppCommand(Group)`
Rapptz/discord.py pull request #8147
Opened 2022-06-12 20:17 UTC by Soheab

## Summary

Fixes #7669 and resolves [card-81287257](https://github.com/Rapptz/discord.py/projects/3#card-81287257)

This PR makes it possible to compare the following classes to the `AppCommand(Group)` modals and itself:

- app_commands.Command
- app_commands.ContextMenu
- app_commands.Group

I renamed the `AppCommand`'s `.to_dict()` method to `.to_comparison_dict()` [as discussed](https://discord.com/channels/336642139381301249/603069307286454290/984789577602592829) in the [discord.py server](https://discord.com/invite/dpy)

I have tested this thoughtfully but not with every possibility but it should be fine...

## Checklist

- [x] If code changes were made then they have been tested.
    - [] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-12 20:22 UTC, Rapptz requested changes
Note that `api_model == user_command` will fail. You need to make sure the `__eq__` and `__ne__` of the app command models return `NotImplemented` when the types differ so it can propagate it back to the user facing types.

That aside, I'm a bit worried about tying the comparison behaviour to `to_dict()`, especially when localisations come into play.

2022-06-12 20:22 UTC, Rapptz commented on discord/app_commands/commands.py
> +
This is already implied

```suggestion
```

2022-06-12 20:22 UTC, Rapptz commented on discord/app_commands/commands.py
> +
This is already implied

```suggestion
```

2022-06-12 20:22 UTC, Rapptz commented on discord/app_commands/models.py
> +            del base['description']
Invert the condition so keys are added rather than removed.

2022-06-12 20:22 UTC, Rapptz commented on discord/app_commands/models.py
> +    def to_comparison_dict(self) -> ApplicationCommandPayload:
```suggestion
    def to_comparison_dict(self) -> Dict[str, Any]:
```

2022-06-12 20:22 UTC, Rapptz commented on discord/app_commands/commands.py
> +        return not self.__eq__(other)
```suggestion
```

2022-06-14 14:28 UTC, Soheab commented
> Note that `api_model == user_command` will fail. You need to make sure the `__eq__` and `__ne__` of the app command models return `NotImplemented` when the types differ so it can propagate it back to the user facing types.

Done, thanks.

> That aside, I'm a bit worried about tying the comparison behaviour to `to_dict()`, especially when localisations come into play.

Doing it with a dict seems like the easiest way IMO as it includes all the values we need to compare and localisations stuff should be the same afaik.

> Also note that by defining `__eq__` you break the hashability of the objects since now there's no `__hash__`, causing test failures.

Fixed. There are still some tests failing but I don't think those are in the scope of this PR?

2022-08-09 12:19 UTC, Rapptz commented
As discussed in the server, I think this feature has kind of become infeasible due to localisation. The original request was also kind of dubious since the server would know nothing changed making the sync call have no side effects.

2022-08-09 12:19 UTC, closed without merging