Add extras attribute to app_commands.Command
Rapptz/discord.py pull request #8163
Opened 2022-06-19 10:07 UTC by nerdguyahmad

## Summary

This pull request adds an `extras` attribute to `app_commands.Command`

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-19 15:44 UTC, PaulMarisOUMary reviewed
Following [discord/interaction.py](https://github.com/Rapptz/discord.py/blob/573bb32a1e31ade15677eb2a945f81729646b546/discord/interactions.py#L115-L118)
https://github.com/Rapptz/discord.py/blob/573bb32a1e31ade15677eb2a945f81729646b546/discord/interactions.py#L115-L118
Moreover, it should be clearer from a developer's point of view reading the docs.

2022-06-19 15:44 UTC, PaulMarisOUMary commented on discord/app_commands/commands.py
> +        A dictionary of user provided extras to attach to this command.
```suggestion
        A dictionary that can be used to store extraneous data.
        The library will not touch any values or keys within this dictionary.
```

2022-06-19 15:44 UTC, PaulMarisOUMary commented on discord/app_commands/commands.py
> +            A dictionary of user provided extras to attach to this command.
```suggestion
            A dictionary that can be used to store extraneous data.
            The library will not touch any values or keys within this dictionary.
```

2022-06-19 15:44 UTC, PaulMarisOUMary commented on discord/app_commands/commands.py
> +        A dictionary of user provided extras to attach to this command.
```suggestion
        A dictionary that can be used to store extraneous data.
        The library will not touch any values or keys within this dictionary.
```

2022-06-19 15:44 UTC, PaulMarisOUMary commented on discord/app_commands/tree.py
> +            A dictionary of user provided extras to attach to this command.
```suggestion
            A dictionary that can be used to store extraneous data.
            The library will not touch any values or keys within this dictionary.
```

2022-06-20 03:03 UTC, Rapptz requested changes
These need to be copied in the various copy methods.

2022-06-22 00:38 UTC, Rapptz approved these changes
LGTM. Thanks.

2022-06-22 00:38 UTC, merged