Support unicode emojis in PartialEmojiConverter
Rapptz/discord.py pull request #8192
Opened 2022-06-29 18:34 UTC by DenverCoder1

## Summary

Previously only custom emojis worked with `PartialEmojiConverter`. An exception would be raised:

`discord.ext.commands.errors.PartialEmojiConversionFailure: Couldn't convert "⏹️" to PartialEmoji.`

This adds support for all kinds of unicode emojis.

Note: The regex is a bit loose but all emojis are covered by the regex.

Test code:

```py
@bot.command()
async def test(ctx: commands.Context[commands.Bot], emoji: discord.PartialEmoji):
    await ctx.message.add_reaction(emoji)
```

![image](https://user-images.githubusercontent.com/20955511/175830618-8e450a74-328c-4e8f-b2f9-b478b1324472.png)

The regex has been tested for correctness using a third-party [emoji](https://pypi.org/project/emoji/) package:

```py
from emoji import UNICODE_EMOJI
import re
# output should be empty
print(*["" if re.match(r"^[\u0023-\u0039]?[\u00ae\u00a9\U00002000-\U0010ffff]+$", argument) else f"{argument} {[hex(ord(c)) for c in argument]}\n" for argument in UNICODE_EMOJI['en']], sep="")
```

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-06-29 18:42 UTC, rtk-rnjn commented
Annotate `emoji` as `Union[PartialEmoji, str]`. Unicode emojis are basically string.

2022-06-29 18:42 UTC, muddyfish commented
This is a breaking change for those who use `.url` or `.read()` on the partial emojis returned

2022-06-29 18:48 UTC, DenverCoder1 commented
> Annotate `emoji` as `Union[PartialEmoji, str]`. Unicode emojis are basically string.

The unicode emoji string is contained within a `PartialEmoji` as the name attribute. So it's still a `PartialEmoji`.

2022-06-29 18:49 UTC, DenverCoder1 commented
> This is a breaking change for those who use `.url` or `.read()` on the partial emojis returned

Those methods already check `if self.is_unicode_emoji():`.

`PartialEmoji` already supports unicode emojis, this PR simply allows the command converter to convert unicode emojis.

2022-06-29 18:51 UTC, muddyfish commented
> > This is a breaking change for those who use `.url` or `.read()` on the partial emojis returned
> 
> Those methods already check `if self.is_unicode_emoji():`.
> 
> `PartialEmoji` already supports unicode emojis, this PR simply allows the command converter to convert unicode emojis.

Previously when using a PartialEmojiConverter, these methods always succeeded and gave useful results. With this change they won't

2022-06-29 19:37 UTC, DenverCoder1 commented
> Previously when using a PartialEmojiConverter, these methods always succeeded and gave useful results. With this change they won't

I'd say that converting unicode emojis is the expected behaviour, so while it's true that someone _might_ be catching PartialEmojiConversionFailure to determine that an argument is not a custom emoji, I find it to be unlikely and a bit of a stretch.

If you want we can call it a breaking change and I'll add it to migrating for now anyway.

2022-06-30 01:54 UTC, ArjunSharda approved these changes

2022-06-30 02:05 UTC, Rapptz requested changes
I don't consider this to be a strict breaking change, however, I don't think this is something I should do because the range of emoji tends to be volatile between unicode versions and that's a maintenance burden historically I didn't want to deal with. That aside, the range in this regex is incredibly wide to the point of being meaningless for its purpose.

Consider a sentence in Japanese:

```py
>>> import re
>>> regex = re.compile(r'^[\u0023-\u0039]?[\u00ae\u00a9\U00002000-\U0010ffff]+$')
>>> regex.match('お前は何してんだ？')
<re.Match object; span=(0, 9), match='お前は何してんだ？'>
```

The reason why this regex works with everything is because it casts such a wide net, basically a large amount of the BMP is being included here. A more proper solution would be to take into consideration the actual ranges that a unicode emoji falls under, and this is very much a best-guess basis. The known ranges, from looking around, are more or less:

- `U+1F1E6` to `U+1F1FF`: Flags
- `U+1F300` to `U+1F5FF`: Misc Symbols and Pictographs
- `U+1F600` to `U+1F64F`: Emoticons
- `U+1F680` to `U+1F6FF`: Transport and Map
- `U+1F900` to `U+1F9FF`: Supplemental Symbols and Pictographs
- `U+2600` to `U+26FF`: Misc Symbols
- `U+2700` to `U+27BF`: Dingbats
- `U+FE00` to `U+FE0F`: Variation Selectors

These ranges are inclusive.

2022-06-30 03:08 UTC, DenverCoder1 commented
> * `U+1F1E6` to `U+1F1FF`: Flags
> * `U+1F300` to `U+1F5FF`: Misc Symbols and Pictographs
> * `U+1F600` to `U+1F64F`: Emoticons
> * `U+1F680` to `U+1F6FF`: Transport and Map
> * `U+1F900` to `U+1F9FF`: Supplemental Symbols and Pictographs
> * `U+2600` to `U+26FF`: Misc Symbols
> * `U+2700` to `U+27BF`: Dingbats
> * `U+FE00` to `U+FE0F`: Variation Selectors

This misses more than half the existing emoji, and Unicode could always be extended.

Using a regex to match emojis with few false positives is very complicated and would be an extremely complicated, long regex.

[This one](https://github.com/mathiasbynens/emoji-regex/blob/main/index.js) for example is over 3,000 characters long.

The simplest, most reliable option would be to just use an external lib method such as [emoji](https://pypi.org/project/emoji/).is_emoji(), but that would require adding dependencies and it seems like it's preferred to avoid that.

Alternatively, it could just be assumed that anything that's not a custom emoji is a unicode emoji (similar to PartialEmoji.from_string) and never raise the error.

Or we could use a very loose regex that will for sure cover everything without being unnecessarily complicated.

2022-06-30 03:23 UTC, Rapptz commented
Right, my point is that this wasn't added because it is complicated to do and is a maintenance burden. A lot of the regex are generated, mainly out of laziness and because they don't want to deal with the post-validity. The post-validity in this case would just be Discord rejecting it, but ideally a regex could be much shorter and cast a smaller net. However, the current regex is far too wide (it's quite literally U+2000 until the end of the unicode range) so that's not going to be very helpful. 

Thanks for the PR but I think I'm just not going to go forward with it.

2022-06-30 03:23 UTC, closed without merging