update docs for abc.Messageable.pins()
Rapptz/discord.py pull request #8234
Opened 2022-07-16 14:09 UTC by ow0x

## Summary

This updates documentation for abc.Messageable.pins() method to account for `discord.Forbidden` error which is raised when the bot doesn't have permission to view the said channel in order to retrieve it's pins. Someone mentioned this in #bikeshedding in dpy server so I decided to make this PR. Please let me know your review!

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-07-16 18:33 UTC, mesub7 requested changes
Really tiny nitpick

2022-07-16 18:33 UTC, mesub7 commented on discord/abc.py
> +            You do not have the permission to view this channel in order to retrieve it's pinned messages.
its not it's

2022-07-16 18:47 UTC, mesub7 approved these changes

2022-07-17 02:13 UTC, ArjunSharda approved these changes

2022-07-17 02:28 UTC, Rapptz reviewed
Need to be consistent with the rest of the library

2022-07-17 02:28 UTC, Rapptz commented on discord/abc.py
> +            You do not have the permission to view this channel in order to retrieve its pinned messages.
```suggestion
            You do not have the permission to retrieve pinned messages.
```

2022-07-17 05:07 UTC, Rapptz approved these changes
Thanks!

2022-07-17 05:07 UTC, merged