Make General Improvements
Rapptz/discord.py pull request #8969
Opened 2022-10-01 08:34 UTC by Infiniticity

## Summary

This PR improves existing code.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-10-01 09:01 UTC, CaedenPH requested changes
All looks very good, but one `f-string` that was actually an `f-string` got turned into a normal string

2022-10-01 09:14 UTC, Infiniticity commented on discord/app_commands/transformers.py
> -                raise TypeError(f'expected tuple for arguments, received {items.__class__.__name__} instead')
I have fixed this.

2022-10-01 09:15 UTC, CaedenPH approved these changes

2022-10-02 21:50 UTC, Rapptz approved these changes
As with all changes that try to enforce some form of consistency, there is no promise that these will be maintained in the future. An empty f-string with no interpolation compiles down to the same thing regardless and could just be vestigial from a refactoring.

The tuple related changes are a nice change though.

2022-10-02 21:50 UTC, merged