added setter method for ChannelSelect.channel_types
Rapptz/discord.py pull request #9068
Opened 2022-11-15 02:09 UTC by cibere

## Summary

When ##9013 was added, it brought the new select menus that discord added. Though ChannelSelect.channel_types did not have a setter method while Select.options does, so I've added the setter method to it 

## Checklist

- [ x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x ] This PR fixes an issue.
- [x ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2022-11-15 06:28 UTC, Rapptz requested changes
In the `ui` module, setters are usually type checked to ensure the invariant is upheld.

2022-11-15 15:50 UTC, cibere commented
> In the `ui` module, setters are usually type checked to ensure the invariant is upheld.

Though the decorator doesn't type check it, so wouldn't inconsistent?

2022-11-17 02:58 UTC, JDJGInc commented
> > In the `ui` module, setters are usually type checked to ensure the invariant is upheld.
> 
> Though the decorator doesn't type check it, so wouldn't that make it inconsistent?

I have confirmed this as it seems that all the other setters in the file look practically the same

2022-11-17 03:03 UTC, Rapptz commented
> Though the decorator doesn't type check it, so wouldn't that make it inconsistent?

Kind of. The decorator doesn't do it but setters do.

> I have confirmed this as it seems that all the other setters in the file look practically the same

Confirmed what? Here's a setter from the `Select` itself:

https://github.com/Rapptz/discord.py/blob/029ed6c46d388c1e07a42b7905f3c17df59bdb9d/discord/ui/select.py#L312-L319

Note that it does type checking to ensure you're not passing it garbage.

2022-11-17 04:32 UTC, JDJGInc commented
Danny, cibere has updated it
 could you please run the checks and check the pull request please?
Thanks

2022-11-17 10:45 UTC, Rapptz approved these changes
Thanks.

2022-11-17 10:46 UTC, merged