Add autocomplete warning about user input
Rapptz/discord.py pull request #9098
Opened 2022-12-01 18:57 UTC by rdrescher909

## Summary

Adds a warning that users may elect to ignore autocomplete suggestions.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

2022-12-01 19:51 UTC, olijeffers0n approved these changes

2022-12-01 20:27 UTC, Ender2K89 approved these changes

2022-12-01 20:29 UTC, JDJGInc commented
Looks good to me

2022-12-01 23:30 UTC, Rapptz requested changes

2022-12-01 23:30 UTC, Rapptz commented on discord/app_commands/commands.py
> +            The results presented to the user are suggestions. The user may ignore them and input their own value.
```suggestion
            The choices returned from this coroutine are suggestions. The user may ignore them and input their own value.
```

2022-12-01 23:30 UTC, Rapptz commented on discord/app_commands/commands.py
> +        The results presented to the user are suggestions. The user may ignore them and input their own value.
```suggestion
        The choices returned from this coroutine are suggestions. The user may ignore them and input their own value.
```

2022-12-01 23:54 UTC, rdrescher909 commented on discord/app_commands/commands.py
> +        The results presented to the user are suggestions. The user may ignore them and input their own value.
Implemented with latest commit

2022-12-01 23:55 UTC, rdrescher909 commented on discord/app_commands/commands.py
> +            The results presented to the user are suggestions. The user may ignore them and input their own value.
Implemented with latest commit.

2022-12-02 11:09 UTC, Rapptz approved these changes
Thanks.

2022-12-02 11:10 UTC, merged