Update create_stage_channel to support all features
Rapptz/discord.py pull request #9245
Opened 2023-02-18 16:32 UTC by NarmyOnDiscord

## Summary

Adds support while creating stage channels for
- bitrate
- user_limit
- rtc_region
- video_quality_mode

Also removes topic, since thats not needed and your code would fail when you try to create a stage channel without a topic.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-02-18 16:33 UTC, Rapptz requested changes
Thanks. These need `versionadded` strings.

2023-02-18 16:34 UTC, NarmyOnDiscord commented
> Thanks. These need `versionadded` strings.

2.2, right?

2023-02-18 16:34 UTC, Rapptz commented on discord/guild.py
> +            options['video_quality_mode'] = video_quality_mode.value
This also needs a type check like the other methods

2023-02-18 19:23 UTC, NarmyOnDiscord reviewed
Added in the last commit

2023-02-19 03:33 UTC, Rapptz approved these changes
Thanks!

2023-02-19 03:34 UTC, merged