Fix scheduled_event param handling
Rapptz/discord.py pull request #9275
Opened 2023-02-28 22:24 UTC by Puncher1

## Summary

**This fix includes following:**
* overloads for `Guild.create_scheduled_event` + not requiring some args
* `end_time` is required now when `entity_type` is `external` in `Guild.create_scheduled_event` 
* `privacy_level` isn't static anymore in `Guild.create_scheduled_event`
* better readability when `entity_type` is not missing for both `Guild.create_scheduled_event` and `ScheduledEvent.edit`

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-02-28 22:44 UTC, Puncher1 commented
@Rapptz For the API call `channel_id` is optional and not forbidden when `entity_type` is `external` but it doesn't have an effect, because `location` must be passed anyway. Should it still be possible to pass a channel in combination with `EntityType.external` or would it be confusing?

2023-02-28 22:46 UTC, Puncher1 commented
Can't find where the issue is of the lint check.

2023-02-28 23:26 UTC, bijij commented
> Can't find where the issue is of the lint check. 

You might be using 2023 black, dpy is pinned to 2022 black

~black devs could have never foreseen this issue~

2023-03-01 13:56 UTC, Rapptz commented
This PR is failing because there's *a lot* of trailing whitespace. Please install black and run it locally.

2023-03-01 20:20 UTC, Puncher1 commented
@Rapptz Ready to merge. In case you didn't see my question:
For the API call `channel_id` is optional even when `entity_type` is `external` but it doesn't have an effect, because `location` must be set anyway. At the moment it throws an error when you provide `channel` in combination with `EntityType.external` even when it technically would work with the API call.

2023-03-01 23:48 UTC, Rapptz commented
> Should it still be possible to pass a channel in combination with EntityType.external or would it be confusing?

The current error is fine since it corresponds to the modal in the client.

2023-03-01 23:49 UTC, Rapptz requested changes

2023-03-01 23:49 UTC, Rapptz commented on discord/guild.py
> +                    entity_type = EntityType.stage_instance
```suggestion
                if channel.type is VoiceChannel:
                    entity_type = EntityType.voice
                elif channel.type is StageChannel:
                    entity_type = EntityType.stage_instance
```

2023-03-02 06:00 UTC, z03h commented
Setting end_time should be outside the entity_type if checks to allow setting an end time for voice/stage events

2023-03-02 09:18 UTC, Puncher1 commented
> Setting end_time should be outside the entity_type if checks to allow setting an end time for voice/stage events

Thanks

2023-03-05 22:28 UTC, Rapptz approved these changes

2023-03-05 22:28 UTC, merged