KeyError 'available' for GuildSticker
Rapptz/discord.py pull request #9324
Opened 2023-03-31 18:21 UTC by justanotherbyte

## Summary

![image](https://user-images.githubusercontent.com/62267480/229199344-643e9765-3c05-4951-b08e-7aee9979ea75.png)

A KeyError is raised for `GuildSticker`s. The documentation states its an optional boolean 
![image](https://user-images.githubusercontent.com/62267480/229199492-7d7e6827-af1e-4fe7-b86f-6102dcb29c06.png)

however discord.py currently doesn't treat it as such. This PR fixes that.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-03-31 23:09 UTC, Rapptz requested changes
Thanks for the PR, there are a few errors though.

2023-03-31 23:09 UTC, Rapptz commented on discord/sticker.py
> +    available: Optional[:class:`bool`]
This is an unnecessary breaking change, please revert it.

2023-03-31 23:09 UTC, Rapptz commented on discord/sticker.py
> +        self.available: Optional[bool] = data.get('available')
This is a breaking change.
```suggestion
        self.available: bool = data.get('available', True)
```

2023-03-31 23:09 UTC, Rapptz commented on discord/types/sticker.py
> +    available: Optional[bool]
```suggestion
    available: NotRequired[bool]
```

2023-04-01 08:50 UTC, justanotherbyte commented
I've gone ahead and made the requested changes

2023-04-01 08:56 UTC, Rapptz approved these changes
Thanks.

2023-04-01 08:57 UTC, merged