Support for voice messages
Rapptz/discord.py pull request #9358
Opened 2023-04-14 22:57 UTC by Puncher1

## Summary

This PR adds support for voice messages. 

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-04-14 23:11 UTC, diceroll123 commented on discord/permissions.py
>          """
might wanna add versionchanged

2023-04-14 23:20 UTC, Puncher1 commented on discord/permissions.py
>          """
Thanks

2023-04-15 14:48 UTC, Puncher1 commented on discord/flags.py
> +    @alias_flag_value
Ah yeah, was a left-over from copy-pasting the above one 😄, thanks!

2023-04-18 04:57 UTC, Rapptz requested changes
Minor nits.

2023-04-18 04:57 UTC, Rapptz commented on discord/message.py
> +        The duration of the audio file. Returns ``None`` if it's not a voice message.
```suggestion
        The duration of the audio file in seconds. Returns ``None`` if it's not a voice message.
```

2023-04-18 04:57 UTC, Rapptz commented on discord/utils.py
> +    return bytes_
```suggestion
    return b64decode(data.encode('ascii'))
```

2023-04-19 17:47 UTC, Puncher1 commented
It's officially documented now.

2023-04-20 04:07 UTC, Rapptz approved these changes

2023-04-20 04:08 UTC, merged