get_message changes
Rapptz/discord.py pull request #964
Opened 2017-12-25 01:53 UTC by khazhyk

- Try first to get message from local cache, save us a discord query
- If unable to use get_message, fallback to logs_from

2018-01-06 22:12 UTC, Rapptz commented
I actually don't like this because `get_message` could be used as a way to bypass the cache as of now when it could potentially be stale due to Discord dropping packets or some strange event.

2018-01-06 22:33 UTC, khazhyk commented
(Noticing also this doesn't filter specifically per channel.)

Perhaps re-introduce bot.messages or similar for trying to grab from local message cache, and users can have their own local-then-remote logic?

2018-01-06 22:40 UTC, Rapptz commented
If something like that were to be introduced it'd have to be something like `Client.get_cached_message` or something.

2019-04-15 00:59 UTC, khazhyk commented
updated this, find_message or whatever will be in separate PR

2019-04-15 01:00 UTC, khazhyk commented
Oh, I guess one issue with this is get_message raises NotFound, whereas logsfrom will return None... could fake that I guess

2019-04-15 01:39 UTC, khazhyk commented
None case is a bit weird
 - different exception raised for using history vs. not is strange
 - changing exception from NotFound to something else is breaking
 - splitting out to different method misses point of having single api bots & users can use

LookupError seems least bad to me?

2020-08-28 21:09 UTC, khazhyk commented on discord/abc.py
> +            data = await self._state.http.logs_from(channel.id, limit=1, before=id + 1)
use around=id limit=1, since discord supports this now

2020-09-05 20:01 UTC, khazhyk commented
Updated to use around=id, this doesn't fix the LookupError vs. HTTPException disparity. Considering this is opt-in behavior anyways, I'm not that sad about the different error, but we could "fake" a httpexception if you think that's better. wdyt?

2020-09-07 20:00 UTC, khazhyk commented
Updated this:
 - Removed use_history=None handling, since we're defaulting all users to True
 - defaulted all users to True
 - added the .. versionadded:: 1.5 stuff?

2020-09-08 02:46 UTC, Rapptz requested changes
It might be worth using the rather rare `deprecated('fetch_message_fast')` decorator on top of regular `fetch_message`.

2020-09-08 02:46 UTC, Rapptz commented on discord/abc.py
> +        Prefer using fetch_message_fast.
```suggestion
        Prefer using :meth:`fetch_message_fast`.
```

2020-09-08 02:46 UTC, Rapptz commented on discord/abc.py
> +    async def fetch_message_fast(self, message_id: int):
```suggestion
    async def fetch_message_fast(self, id):
```

2020-09-08 03:02 UTC, khazhyk commented
Thanks, updated

2020-09-08 03:03 UTC, Rapptz approved these changes

2020-09-08 03:04 UTC, merged