Add new incident message types
Rapptz/discord.py pull request #9686
Opened 2023-12-14 21:20 UTC by Puncher1

## Summary

This PR adds the following new incident message types:  `guild_incident_alert_mode_enabled` `guild_incident_alert_mode_disabled`, `guild_incident_report_raid`, `guild_incident_report_false_alarm`

I'm not sure what `guild_incident_report_false_alarm` is exactly. I've derived the description now from the name.

## Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2023-12-14 23:58 UTC, Rapptz commented
This is missing the corresponding edit in `Message.system_content`.

2023-12-17 17:48 UTC, Puncher1 commented
Done. `self.author.name` is wrong though since the username change. It should be `self.author.global_name` for every system message, but maybe something for another PR.

2023-12-18 03:57 UTC, Rapptz requested changes
The dt string looks like ISO8601 format so just use the parser for it and the built-in utils.

2023-12-18 03:57 UTC, Rapptz commented on discord/message.py
> +            return f'{self.author.name} enabled security actions until {dt_content}.'
```suggestion
            dt = utils.parse_time(self.content)
            dt_content = utils.format_dt(dt)
            return f'{self.author.name} enabled security actions until {dt_content}.'
```

2023-12-18 03:57 UTC, Rapptz commented on discord/message.py
> +        in UTC.
```suggestion
        returns an English message denoting the contents of the system message.
```

2023-12-18 22:45 UTC, Rapptz approved these changes
Thanks.

2023-12-18 22:45 UTC, merged