Add ButtonStyle.premium
Rapptz/discord.py pull request #9845
Opened 2024-05-25 15:04 UTC by DA-344

## Summary

DDevs Docs PR: https://github.com/discord/discord-api-docs/pull/6875

Removes ``InteractionResponse.require_premium`` in favor of ``ButtonStyle.premium`` like button components.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2024-05-26 22:16 UTC, AbstractUmbra commented
This is *not* a breaking change, for what it's worth.

No contract has been broken since `.require_premium` never made it to a published release. I would argue that this checkbox could be removed from this PR.
Breaking changes do not happen between major version releases - if this is actually a breaking change, it will need to wait until 3.x!

2024-05-30 03:29 UTC, Rapptz requested changes

2024-05-30 03:29 UTC, Rapptz commented on discord/enums.py
> +    gradient = 6
```suggestion
```

2024-05-30 03:29 UTC, Rapptz commented on discord/ui/button.py
> +        The SKU ID this button sends you to. Can't be combined with ``url``.
Missing versionadded.

2024-05-30 03:29 UTC, Rapptz commented on docs/interactions/api.rst
> +        An alias for :attr:`premium`
```suggestion
```

2024-05-30 03:29 UTC, Rapptz commented on docs/interactions/api.rst
> +        required to perform this action.
Missing versionadded.

2024-05-30 03:29 UTC, Rapptz commented on discord/ui/button.py
> +        """Optional[:class:`int`]: The SKU ID this button sends you to."""
Missing versionadded.

2024-05-30 03:29 UTC, Rapptz commented on discord/components.py
> +        'sku_id',
Missing documentation + versionadded.

2024-06-01 07:48 UTC, Rapptz approved these changes

2024-06-01 07:48 UTC, merged