Add support for messages with type purchase_notification
Rapptz/discord.py pull request #9906
Opened 2024-08-06 15:21 UTC by Soheab

## Summary

Relevant docs PR/Discussions:
- https://github.com/discord/discord-api-docs/pull/6927
- https://github.com/discord/discord-api-docs/discussions/6935#discussioncomment-9786723

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2024-08-06 18:19 UTC, Soheab commented on discord/message.py
> +        if guild_product_purchase is not None:
The value can be null according to the [unofficial api docs](https://docs.discord.sex/resources/message#message-purchase-notification-structure) so I guess I don't need to use .get()

2024-08-06 18:20 UTC, Soheab commented on discord/message.py
> +            if guild_product_purchase is not None:
But it can be None?

2024-08-28 19:37 UTC, Rapptz requested changes

2024-08-28 19:37 UTC, Rapptz commented on discord/message.py
> +    """The name of the product that the user has purchased."""
We don't use NamedTuple in the public API if we can help it. Please just turn this into a regular class.

2024-08-28 19:37 UTC, Rapptz commented on docs/api.rst
> +.. autoclass:: PurchaseNotification
```suggestion
.. autoclass:: PurchaseNotification()
```

2024-08-28 19:37 UTC, Rapptz commented on docs/api.rst
> +.. attributetable:: GuildProductPurchase()
```suggestion
.. attributetable:: GuildProductPurchase
```

2024-10-09 21:21 UTC, Rapptz requested changes
Just some minor nits

2024-10-09 21:21 UTC, Rapptz commented on discord/message.py
> +        return self.listing_id >> 22
`__hash__` with no `__eq__` is weird, you should define both if you're going to do that.

2024-10-09 21:21 UTC, Rapptz commented on discord/message.py
> +
This is missing `__slots__`.

2024-10-10 23:42 UTC, Rapptz approved these changes

2024-10-10 23:43 UTC, merged