Message Forwarding
Rapptz/discord.py pull request #9950
Opened 2024-09-29 17:01 UTC by DA-344

## Summary

[redmvc said in #9892](https://github.com/Rapptz/discord.py/pull/9892#issuecomment-2380867248) they will not be able to continue with the PR anytime soon so I've continued their work in this PR.

This has all the previous changes in addition of:
- `PartialMessage.forward(...)` method for message forwarding
- `MessageReference` constructor not a breaking change
- Docs fixes
- `.. versionadded::`s where it was missing.

**Related Discord API Docs PRs**:
- https://github.com/discord/discord-api-docs/pull/6833
- https://github.com/discord/discord-api-docs/pull/7116

## Checklist

- [ ] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2024-10-09 21:32 UTC, Rapptz reviewed
This looks good but there are unfortunately merge conflicts.

2024-10-09 21:32 UTC, Rapptz commented on discord/enums.py
> +    default = 0
```suggestion
class MessageReferenceType(Enum):
    default = 0
    reply = 0
    forward = 1
```

2024-10-09 21:56 UTC, Rapptz requested changes
Sorry, I forgot this PR also introduces instances of `Optional[List[X]]`.

2024-10-09 21:56 UTC, Rapptz commented on discord/message.py
> +    message_snapshots: Optional[List[:class:`MessageSnapshot`]]
```suggestion
    message_snapshots: List[:class:`MessageSnapshot`]
```

`Optional[List[X]]` is silly.

2024-10-10 14:14 UTC, DA-344 commented on discord/message.py
> +    message_snapshots: Optional[List[:class:`MessageSnapshot`]]
Updated on the latest commit.

2024-10-10 14:34 UTC, DA-344 commented
Merge conflicts have been resolved and suggestions have been commited, PR is now ready to be merged.

2024-10-10 23:49 UTC, Rapptz commented
This has conflicts again.

2024-10-11 14:30 UTC, DA-344 commented
Fixed merge conflicts again.

2024-10-11 19:34 UTC, merged